/*
 * Phase A4 — arm64 kernel-CGO symbol probe.
 *
 * What this is: a tiny standalone aarch64 binary, run under
 * qemu-aarch64-static, that opens KERNEL.CGO, walks the main-segment
 * link table of its first object (gcommon), and prints a stable
 * non-zero integer derived from the LINK_SYMBOL_OFFSET records.
 *
 * Why this matters for A4: A4 widened the ObjectGenerator with arm64
 * imm12 / imm21 / imm19 fix-up handling so the encoder can register
 * symbol/static/function references that the linker resolves. The
 * differential harness validates the encoder side; this probe
 * validates the LINK-TABLE side end-to-end on arm64. It exercises:
 *
 *   - File I/O (read of the CGO from disk) under qemu-aarch64
 *   - 32-bit / 16-bit little-endian decoding of the DgoHeader and
 *     ObjectHeader structures (the GOAL kernel's view of an object)
 *   - The v3 link-table walker (LINK_SYMBOL_OFFSET, LINK_TYPE_PTR,
 *     LINK_DISTANCE_TO_OTHER_SEG_32, LINK_PTR record kinds) — which
 *     is what the kernel's symlink_v3 / cross_seg_dist_link_v3 /
 *     ptr_link_v3 / typelink_v3 walkers do at runtime.
 *
 * Probe output (single line, single integer):
 *
 *   The 8-bit FNV-1a hash of the SORTED list of symbol names found
 *   in LINK_SYMBOL_OFFSET records of the first object's main
 *   segment, multiplied by the count of distinct LINK_SYMBOL_OFFSET
 *   records (so the value is at least the count and bounded away
 *   from zero by the hash byte).
 *
 *   The combination is deterministic (KERNEL.CGO is regenerated by
 *   goalc with a stable layout) and bound to be in the
 *   thousands-to-millions range — comfortably non-zero and not a
 *   round-number constant that could be hand-spoofed.
 *
 * Build / run:  see .autoport/lib/run_a4_probe.sh
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

/* Link-table record kinds — must match common/link_types.h.
 * Duplicated here so the probe is freestanding (no GOAL headers). */
#define LINK_TABLE_END 0
#define LINK_SYMBOL_OFFSET 1
#define LINK_TYPE_PTR 2
#define LINK_DISTANCE_TO_OTHER_SEG_64 3
#define LINK_DISTANCE_TO_OTHER_SEG_32 4
#define LINK_PTR 5

#define MAX_SYMBOLS 4096
#define MAX_NAME 256

static uint32_t read_u32(const uint8_t* p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

static uint16_t read_u16(const uint8_t* p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}

/* FNV-1a 32-bit, applied byte-by-byte to a string. */
static uint32_t fnv1a(const char* s) {
    uint32_t h = 0x811c9dc5u;
    for (; *s; s++) {
        h ^= (uint8_t)*s;
        h *= 16777619u;
    }
    return h;
}

static int cmp_strings(const void* a, const void* b) {
    const char* sa = *(const char* const*)a;
    const char* sb = *(const char* const*)b;
    return strcmp(sa, sb);
}

int main(int argc, char** argv) {
    const char* path = (argc > 1) ? argv[1] : "out/jak1/iso/KERNEL.CGO";
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "probe: cannot open %s\n", path);
        return 2;
    }
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (fsize < 64) {
        fprintf(stderr, "probe: file too small\n");
        fclose(f);
        return 2;
    }
    uint8_t* buf = malloc((size_t)fsize);
    if (!buf || fread(buf, 1, (size_t)fsize, f) != (size_t)fsize) {
        fprintf(stderr, "probe: read failed\n");
        fclose(f);
        free(buf);
        return 2;
    }
    fclose(f);

    /* DgoHeader: u32 count + char name[60]. */
    uint32_t obj_count = read_u32(buf);
    if (obj_count == 0 || obj_count > 256) {
        fprintf(stderr, "probe: bogus object_count=%u\n", obj_count);
        free(buf);
        return 2;
    }

    /* First object body starts at offset 64 (DgoHeader). */
    uint32_t off = 64;
    uint32_t obj_size = read_u32(buf + off);
    /* ObjectHeader is 64 bytes; GOAL v3 object follows. */
    uint8_t* o = buf + off + 64;
    long o_size = (long)obj_size - 64;
    if (o_size < 68 || o + 4 > buf + fsize) {
        fprintf(stderr, "probe: first object too small\n");
        free(buf);
        return 2;
    }
    if (memcmp(o, "GOAL", 4) != 0) {
        fprintf(stderr, "probe: missing GOAL magic on first object\n");
        free(buf);
        return 2;
    }

    /* v3 layout:
     *   +0   "GOAL"
     *   +4   u16 major, u16 minor
     *   +8   u32 obj_ver (=3)
     *   +12  u32 segment_count (=3)
     *   +16  SizeOffsetTable: 6 entries of (u32 offset, u32 size) =
     *        link_segs[3] then code_segs[3]
     *   +64  u32 code_base
     *   +68  link tables (segs 2,1,0 packed)
     *   +code_base  code segments
     *
     * For the main segment (index 0):
     *   link_segs[0].offset is post-GOAL — add 4 for absolute.
     */
    if (read_u32(o + 8) != 3) {
        fprintf(stderr, "probe: object_version != 3\n");
        free(buf);
        return 2;
    }
    /* SizeOffsetTable entries 0..2 are link_segs, 3..5 are code_segs. */
    uint32_t main_link_off = read_u32(o + 16 + 0 * 8);
    uint32_t main_link_sz  = read_u32(o + 16 + 0 * 8 + 4);
    uint32_t link_abs = main_link_off + 4;
    if ((long)(link_abs + main_link_sz) > o_size) {
        fprintf(stderr, "probe: main link out of range\n");
        free(buf);
        return 2;
    }
    uint8_t* lp = o + link_abs;
    uint8_t* lp_end = lp + main_link_sz;

    /* Walk the link table and collect distinct LINK_SYMBOL_OFFSET names. */
    char* sym_names[MAX_SYMBOLS];
    int n_syms = 0;
    int sym_records = 0;
    while (lp < lp_end) {
        uint8_t kind = *lp++;
        if (kind == LINK_TABLE_END) {
            break;
        } else if (kind == LINK_SYMBOL_OFFSET) {
            /* C-string symbol name, NUL terminator. */
            char name[MAX_NAME];
            int n = 0;
            while (lp < lp_end && *lp && n + 1 < MAX_NAME) {
                name[n++] = (char)*lp++;
            }
            name[n] = 0;
            if (lp < lp_end) lp++;  /* skip NUL */
            if (lp + 4 > lp_end) break;
            uint32_t n_off = read_u32(lp); lp += 4;
            lp += n_off * 4;  /* skip the s32 offset list */
            sym_records++;
            /* Deduplicate by linear scan; n is tiny enough. */
            int found = 0;
            for (int i = 0; i < n_syms; i++) {
                if (strcmp(sym_names[i], name) == 0) { found = 1; break; }
            }
            if (!found && n_syms < MAX_SYMBOLS) {
                sym_names[n_syms] = strdup(name);
                if (!sym_names[n_syms]) break;
                n_syms++;
            }
        } else if (kind == LINK_TYPE_PTR) {
            while (lp < lp_end && *lp) lp++;
            if (lp < lp_end) lp++;  /* NUL */
            if (lp < lp_end) lp++;  /* method count u8 */
            if (lp + 4 > lp_end) break;
            uint32_t n_off = read_u32(lp); lp += 4;
            lp += n_off * 4;
        } else if (kind == LINK_DISTANCE_TO_OTHER_SEG_32 ||
                   kind == LINK_DISTANCE_TO_OTHER_SEG_64) {
            lp += 1 + 4 + 4 + 4;  /* target_seg + 3 u32 */
        } else if (kind == LINK_PTR) {
            lp += 4 + 4;
        } else {
            fprintf(stderr, "probe: unknown link kind %u\n", kind);
            free(buf);
            return 2;
        }
    }

    /* Sort names so the FNV1a hash is order-independent. */
    qsort(sym_names, (size_t)n_syms, sizeof(sym_names[0]), cmp_strings);

    /* Hash the concatenation of names. The 8 low bits of the hash
     * mixed with the record count gives a value in
     * [sym_records, sym_records * 256] — comfortably non-zero. */
    uint32_t h = 0x811c9dc5u;
    for (int i = 0; i < n_syms; i++) {
        for (const char* c = sym_names[i]; *c; c++) {
            h ^= (uint8_t)*c;
            h *= 16777619u;
        }
        h ^= '\n';
        h *= 16777619u;
    }
    uint32_t result = (uint32_t)sym_records * (uint32_t)((h & 0xff) + 1);

    printf("%u\n", result);

    for (int i = 0; i < n_syms; i++) free(sym_names[i]);
    free(buf);
    return 0;
}
