#!/usr/bin/env python3
"""Cycle 14 — per-link EXTREMAL skinned-vertex offsets, in bone-local bind space.
Cycle 18 — plus the BODY side as REAL SURFACE: per body bone, surface sample points WITH
OUTWARD NORMALS (`bs` records), so the runtime can compute a SIGNED distance from a chain
point to the character's actual skinned surface instead of to a fitted capsule.  SPEC §18:
the fitted proxies measured a median radius of 967 units and a max of 13646 on a 9420-unit
character, and the `fit error = 0` that hid it was a tautology (a volume fitted to a bone's
own vertices contains them by construction).  The capsules survive only as broad phase.

Cycle 14 diagnosis: the audit measured BONES while the owner sees the MESH — the mayor's
bow links sat within tolerance while his skinned ribbon pierced his belly.  The runtime
therefore needs, per physics chain link, the handful of skinned vertices that stick out
FURTHEST from the link (perpendicular extremes in four quadrants, plus the axial tip
overhang), expressed in the bone's own bind-local frame so they can be carried by the
solved link transform every frame and tested against the body volumes at the SURFACE.

Everything geometric is reused from physics_c6_volumes.py (same GLB sources, same unit
convention: glTF metres x 4096 = game units, same WMIN vertex-ownership threshold).

Record grammar written to physics_mesh.txt:
  ms <chain> <link> <n> (x y z)*n           per chain LINK, bone-local bind space, game units
  bs <bone> <n> (x y z nx ny nz)*n          per BODY bone, same space; n unit outward normal

Outputs:
  * recharged_assets/physics_mesh.txt                 the data file the C++ runtime parses
  * .autoport/reports/Grecharged-secondary-motion/mesh_extents_c14.txt   the audit
    (NOT rewritten by --bsurf-only, which only touches the `bs` lines of the data file)

Usage:  python3 .autoport/physics_c14_meshsamples.py [--bsurf-only]
"""
import argparse
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import physics_c6_volumes as c6  # noqa: E402  (GLB loading, chains-file parsing, WMIN)
from retarget_hd_models import (read_glb, consolidate_buffers, read_accessor,  # noqa: E402
                                skin_info)

REPO = c6.REPO
CHAINS = c6.CHAINS
WMIN = c6.WMIN
UNITS = c6.UNITS
MIN_CLOUD = c6.MIN_CLOUD      # a bone owning fewer dominant vertices carries no surface
PRUNE_MARGIN = 8.0            # a sample within (link radius + this) adds nothing beyond
                              # the existing center+radius test — dropped, and counted.
BSURF_MAX = 12                # surface samples per body bone (farthest-point sampled)
BSURF_MIN_SPREAD = 1.0        # samples collapsing inside this span are one point, not a surface
# STRAY-VERTEX CAP, RELATIVE TO THE BONE'S OWN SPAN.  A `bs` sample is an offset from the bone
# ORIGIN, and a bone's flesh runs the bone's own LENGTH, so a flat absolute bound is a hole
# generator and not an outlier filter: at a flat 2048 units this script dropped 18.53% of all
# body-bone vertices, including 77 of the 109 vertices of mayor-lod0's `chest` (median 2147 on a
# 2558-unit chest->neck span) — i.e. it deleted the very surface the mayor's bow is supposed to
# be measured against.  The bound is therefore the bone's own reach:
#     span = max(|bone - parent|, max over children |bone - child|)
#     cap  = max(BSURF_SPAN_K * span, BSURF_MIN_CAP)
# which still catches real stray weighting (keira-hd lTopStrap2: a 20-vertex cloud sitting 6248
# units out on a 1366-unit bone) because that is many times the bone's own reach.
BSURF_SPAN_K = 2.0
BSURF_MIN_CAP = 512.0         # floor, for tip bones whose span is ~0
CHAR_UNITS = 9420.0           # a jak1 character height — used ONLY as a fallback bound when a
                              # model's own extent is unknown.  It is NOT a validity limit: this
                              # cast contains giants (ogreboss measures 59701 units across and
                              # its Relbow bone alone spans 34651), so the absurdity gate below
                              # is the MODEL'S OWN largest bbox side, never a fixed number.
OUT_MESH = os.path.join(REPO, 'recharged_assets', 'physics_mesh.txt')
OUT_REPORT = os.path.join(REPO, '.autoport', 'reports', 'Grecharged-secondary-motion',
                          'mesh_extents_c14.txt')
HEADER = [
    '# physics_mesh.txt — per-link extremal skinned-vertex offsets '
    '(bone-local bind space, game units)',
    '# generated by .autoport/physics_c14_meshsamples.py — derived data, '
    'DO NOT hand-tune',
    '# ms <chain> <link> <n> (x y z)*n           chain LINK: extremal skinned-vertex offsets',
    '# bs <bone> <n> (x y z nx ny nz)*n          BODY bone: surface samples + outward '
    'unit normals',
    '# bs samples are written in farthest-point order: the first k of a bone\'s n samples are a '
    'valid',
    '# (and near-optimal) k-point subset, so a runtime may take a prefix without losing coverage.',
]


def load_geometry_ibm(model):
    """c6.load_geometry plus each joint's inverseBindMatrix (glTF metres, column-major
    already transposed to row convention by skin_info)."""
    geo = c6.load_geometry(model)
    if geo is None:
        return None
    js, bufs = read_glb(geo['path'])
    binc = consolidate_buffers(js, bufs)
    _names, ibms, _parent = skin_info(js, binc)
    geo['ibms'] = ibms
    return geo


def to_bone_local(ibm, pts_game):
    """world bind position (GAME units) -> this bone's local frame (GAME units).

    The IBM is in GLB metres; the rotation part is unit-invariant and the translation
    scales by UNITS, so transforming the game-unit point directly with a scaled
    translation is exactly the metres-space transform followed by x4096."""
    return pts_game @ ibm[:3, :3].T + ibm[:3, 3] * UNITS


def joint_cloud(geo, j):
    """indices of vertices holding >= WMIN of their weight on joint j (same rule as
    c6.link_radius: a vertex may belong to several links, on purpose)."""
    J, W = geo['J'], geo['W']
    sel = np.zeros(len(geo['V']), dtype=bool)
    for c in range(J.shape[1]):
        sel |= (J[:, c] == j) & (W[:, c] >= WMIN)
    return np.flatnonzero(sel)


def perp_basis(axis):
    """two unit vectors orthogonal to axis (and each other) for quadrant binning."""
    ref = np.array([1.0, 0.0, 0.0]) if abs(axis[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    e1 = np.cross(axis, ref)
    e1 /= np.linalg.norm(e1)
    e2 = np.cross(axis, e1)
    return e1, e2


def link_radii_from_chain(ch, nlinks):
    """per-link radius from the chain line's radii= comma list (fallback radius=)."""
    fall = float(ch.kv('radius') or 0.0)
    rtxt = ch.kv('radii')
    if not rtxt:
        return [fall] * nlinks
    vals = [float(x) for x in rtxt.split(',') if x]
    if not vals:
        return [fall] * nlinks
    return [vals[min(i, len(vals) - 1)] for i in range(nlinks)]


def process_link(geo, jidx, li, chain_idx, rad):
    """-> dict(samples=[(x,y,z)...], perp_max, axial_over, nverts) for link li of a chain
    whose resolved joint indices are chain_idx.  All numbers in GAME units, bone-local."""
    j = chain_idx[li]
    ibm = geo['ibms'][j]
    P = geo['P']
    cloud = joint_cloud(geo, j)
    if len(cloud) == 0:
        return dict(samples=[], perp_max=0.0, axial_over=0.0, nverts=0)
    off = to_bone_local(ibm, geo['V'][cloud])          # bone-local offsets, game units

    # sanity on the unit/matrix convention, in two parts, both asserted:
    #  1. IBM @ (this joint's own bind position) is 0 by definition of a bind matrix —
    #     a wrong transpose or an unscaled translation breaks this immediately.
    #  2. where the IBM is near-RIGID (singular values ~1), it preserves lengths, so
    #     |off_local| must match the world vertex-to-bone distance.  Some rigs carry
    #     genuine bind scale (keira-hd joints reach s=9.68); there the runtime's skinning
    #     uses that same scaled IBM, so the scaled offsets are the correct ones and only
    #     check 1 applies.
    self_local = to_bone_local(ibm, P[j][None, :])[0]
    span = float(np.max(np.linalg.norm(geo['V'][cloud] - P[j], axis=1))) + 1.0
    assert np.linalg.norm(self_local) <= max(1.0, 1e-3 * span), \
        'joint %s does not map to its own local origin (|%.3f|) — unit/IBM ' \
        'convention broken' % (geo['names'][j], float(np.linalg.norm(self_local)))
    sv = np.linalg.svd(ibm[:3, :3], compute_uv=False)
    if 0.99 <= sv.min() and sv.max() <= 1.01:
        world_d = np.linalg.norm(geo['V'][cloud] - P[j], axis=1)
        med_w = float(np.median(world_d))
        if med_w > 1.0:
            ratio = float(np.median(np.linalg.norm(off, axis=1))) / med_w
            assert 0.9 <= ratio <= 1.1, \
                'bone-local offsets do not match world distances (ratio %.3f) — ' \
                'unit/IBM convention broken for joint %s' % (ratio, geo['names'][j])

    # axis: bone-local direction toward the NEXT link joint (tip: FROM the previous
    # joint; single-link chain: from the parent bone).
    seglen = 0.0
    if li + 1 < len(chain_idx):
        nxt = to_bone_local(ibm, P[chain_idx[li + 1]][None, :])[0]
        axis, seglen = nxt, float(np.linalg.norm(nxt))
    elif li > 0:
        prv = to_bone_local(ibm, P[chain_idx[li - 1]][None, :])[0]
        axis = -prv                                    # direction FROM the previous joint
    else:
        p = geo['parent'][j]
        if p is not None and 0 <= p < len(P) and np.all(np.isfinite(P[p])):
            axis = -to_bone_local(ibm, P[p][None, :])[0]
        else:
            axis = np.array([0.0, 1.0, 0.0])
    n = float(np.linalg.norm(axis))
    axis = axis / n if n > 1e-6 else np.array([0.0, 1.0, 0.0])

    d_axial = off @ axis
    perp = off - np.outer(d_axial, axis)
    d_perp = np.linalg.norm(perp, axis=1)
    over = np.maximum(0.0, d_axial - seglen)           # mesh past the bone segment

    e1, e2 = perp_basis(axis)
    quad = (np.arctan2(perp @ e2, perp @ e1) >= 0).astype(int) * 2 \
        + (np.abs(np.arctan2(perp @ e2, perp @ e1)) > np.pi / 2).astype(int)
    picks = []
    for q in range(4):
        m = np.flatnonzero(quad == q)
        if len(m):
            picks.append(int(m[np.argmax(d_perp[m])]))
    ax_i = int(np.argmax(d_axial))
    if d_axial[ax_i] > seglen and ax_i not in picks:   # tip overhang: 5th sample
        picks.append(ax_i)

    thr = rad + PRUNE_MARGIN
    samples = []
    for i in picks:
        if d_perp[i] <= thr and over[i] <= thr:
            continue                                   # inside the center+radius test
        samples.append(tuple(round(float(x), 1) for x in off[i]))
    # dedupe (two quadrant maxima can round to the same vertex position)
    seen, uniq = set(), []
    for s in samples:
        if s not in seen:
            seen.add(s)
            uniq.append(s)
    return dict(samples=uniq[:5], perp_max=float(np.max(d_perp)),
                axial_over=float(np.max(over)), nverts=int(len(cloud)))


# ----------------------------------------------------------------------------------------------
# (SPEC §18) BODY SURFACE — real skinned surface samples with outward normals, per body bone
# ----------------------------------------------------------------------------------------------
def load_surface(geo):
    """-> dict(N=per-vertex OUTWARD unit normals aligned with geo['V'], good=bool mask).

    Vertex compaction is recomputed with the SAME rule as c6._gather_model_vertices (the sorted
    set of vertex ids the primitives index into the level-wide merc pool), so triangle indices
    land on geo['V'] rows; the equality of the two counts is asserted, never assumed.

    WINDING, measured not guessed: the merc rip writes strip-order triangle LISTS whose winding
    ALTERNATES every triangle.  On keira-highres-lod0 the sign of (face normal . authored vertex
    normals) over the 10808 faces reads -1 +1 -1 +1 ... and the raw area-weighted accumulation
    cancels to noise — median dot with the authored normals -0.05, i.e. no outward direction at
    all.  Each face is therefore oriented against the glTF NORMAL of its own three vertices
    before the sum, which brings that median to +0.98.  |cross| = 2 * area, so summing the
    UN-normalised cross products is exactly the area weighting the spec asks for.
    """
    js, bufs = read_glb(geo['path'])
    binc = consolidate_buffers(js, bufs)
    used = set()
    prims, nrm_accs = [], set()
    for mesh in js.get('meshes', []):
        for pr in mesh.get('primitives', []):
            if 'indices' not in pr:
                continue
            ind = read_accessor(js, binc, pr['indices']).reshape(-1).astype(np.int64)
            used.update(ind.tolist())               # same `used` set c6 builds
            if pr.get('mode', 4) == 4 and len(ind) >= 3:
                prims.append(ind[:len(ind) // 3 * 3].reshape(-1, 3))
            if 'NORMAL' in pr['attributes']:
                nrm_accs.add(int(pr['attributes']['NORMAL']))
    if not used:
        return None
    idx = np.fromiter(sorted(used), dtype=np.int64)
    assert len(idx) == len(geo['V']), \
        'vertex compaction differs from c6 (%d vs %d) — the two datasets would disagree' \
        % (len(idx), len(geo['V']))
    assert len(nrm_accs) <= 1, 'per-primitive NORMAL accessors (%s) — winding repair would ' \
        'mix pools' % sorted(nrm_accs)
    remap = np.full(int(idx.max()) + 1, -1, dtype=np.int64)
    remap[idx] = np.arange(len(idx))
    V = geo['V']
    if not prims:
        return dict(N=np.zeros_like(V), good=np.zeros(len(V), dtype=bool), ntri=0)
    T = remap[np.concatenate(prims, axis=0)]
    assert not (T < 0).any(), 'triangle references a vertex outside the compacted array'
    fn = np.cross(V[T[:, 1]] - V[T[:, 0]], V[T[:, 2]] - V[T[:, 0]])
    if nrm_accs:
        NA = read_accessor(js, binc, nrm_accs.pop()).astype(np.float64)
        assert len(NA) > int(idx.max()), 'NORMAL accessor shorter than the POSITION pool'
        NA = NA[idx]
        ref = NA[T[:, 0]] + NA[T[:, 1]] + NA[T[:, 2]]
        # DO NOT "SIMPLIFY" THIS AWAY: without the flip the winding alternates every triangle
        # (strip order) and the accumulated normals are noise — see the docstring measurement.
        fn = np.where((np.sum(fn * ref, axis=1) < 0.0)[:, None], -fn, fn)
    N = np.zeros_like(V)
    for c in range(3):
        np.add.at(N, T[:, c], fn)
    ln = np.linalg.norm(N, axis=1)
    good = ln > 1e-9
    N = np.where(good[:, None], N / np.maximum(ln, 1e-12)[:, None], 0.0)
    return dict(N=N, good=good, ntri=int(len(T)))


def farthest_points(pts, k):
    """Deterministic farthest-point sampling: seed = the point furthest from the cloud centroid,
    then repeatedly the point whose distance to the already chosen set is largest.  Ties go to
    the lowest index (np.argmax), so the same cloud always yields the same samples.  Coverage of
    the bone's surface is the point — 12 nearest neighbours would describe one patch.

    THE RETURN ORDER IS THE FPS ORDER AND NOTHING MAY RE-SORT IT.  The runtime keeps a PREFIX of
    each bone's samples (8 of 12 today, all 12 at a higher precision level, without regenerating
    this file), and a prefix of a farthest-point sequence is a valid near-optimal subset of that
    size — a property that index order does NOT have.  The loop therefore runs even when the
    cloud is smaller than k, where returning range(n) would have handed the runtime an arbitrary
    8 of 10 vertices instead of the best-spread 8."""
    n = len(pts)
    k = min(k, n)
    if n == 0:
        return []
    c = pts.mean(axis=0)
    first = int(np.argmax(np.linalg.norm(pts - c, axis=1)))
    picks = [first]
    chosen = np.zeros(n, dtype=bool)
    chosen[first] = True
    d = np.linalg.norm(pts - pts[first], axis=1)
    d[first] = -1.0
    while len(picks) < k:
        i = int(np.argmax(d))
        if d[i] <= 0.0:
            # everything left is an exact duplicate of a point already picked, so it adds zero
            # coverage and the order among them cannot matter — take them in index order.  They
            # are kept, not dropped: duplicated positions carry distinct seam normals.
            for j in np.flatnonzero(~chosen)[:k - len(picks)]:
                picks.append(int(j))
                chosen[j] = True
            break
        picks.append(i)
        chosen[i] = True
        d = np.minimum(d, np.linalg.norm(pts - pts[i], axis=1))
        d[chosen] = -1.0
    return picks


def bone_rotation(ibm):
    """The ROTATION of the bone's inverse bind matrix, with any bind SCALE stripped — the polar
    factor R of A = R S, obtained from the SVD (A = U E V^T -> R = U V^T).  Normals do not
    scale: a non-uniformly scaled bone would otherwise tilt every normal it carries, and a
    uniform scale would only be undone by the re-normalisation.  A mirrored bone (det < 0) keeps
    its reflection, which is the orientation map its own vertices went through."""
    U, _E, Vt = np.linalg.svd(ibm[:3, :3])
    return U @ Vt


def bone_span(geo, kids, j):
    """The bone's own reach: the longer of (bone -> parent) and (bone -> furthest child).  This
    is the length its flesh runs along, which is what the stray cap must be relative to."""
    P, parent = geo['P'], geo['parent']
    span = 0.0
    p = parent[j]
    if p is not None and 0 <= p < len(P) and np.all(np.isfinite(P[p])):
        span = float(np.linalg.norm(P[j] - P[p]))
    for c in kids[j]:
        if np.all(np.isfinite(P[c])):
            span = max(span, float(np.linalg.norm(P[c] - P[j])))
    return span


def bone_surface(geo, surf, cloud, j, cap):
    """-> dict(samples=[(x,y,z,nx,ny,nz)...], nfallback, ndropped, maxoff, maxoff_raw) for one
    body bone, or None if nothing survives.  Bone-local BIND space, game units.

    POSITION is the offset of the vertex from the bone's own origin expressed in the bone's own
    axes (to_bone_local, i.e. IBM applied to the bind-pose world vertex), which is the convention
    the runtime already consumes for `ms`: world = bone_origin + x*row0 + y*row1 + z*row2.
    NORMAL is the area-weighted vertex normal turned by the same bone rotation, scale stripped,
    no translation term, re-normalised.  A vertex with no usable triangle normal falls back to
    the direction from the bone origin — counted, never silent.

    Vertices further than `cap` (the bone's own span-relative bound) from their own bone origin
    are dropped BEFORE the farthest-point sampling, not after: farthest-point seeds on the
    furthest point, so a single stray-weighted vertex would otherwise capture the seed and
    several of the 12 picks."""
    ibm = geo['ibms'][j]
    local = to_bone_local(ibm, geo['V'][cloud])
    d = np.linalg.norm(local, axis=1)
    maxoff_raw = float(np.max(d))
    keep = np.flatnonzero(d <= cap)
    ndrop = int(len(cloud) - len(keep))
    base = dict(samples=[], nfallback=0, ndropped=ndrop, maxoff=0.0, maxoff_raw=maxoff_raw)
    if len(keep) < 2:
        return dict(base, reason='stray')
    local, cloud = local[keep], cloud[keep]
    picks = farthest_points(local, BSURF_MAX)
    P = local[picks]
    spread = float(np.max(np.linalg.norm(P[:, None, :] - P[None, :, :], axis=2)))
    if spread < BSURF_MIN_SPREAD:
        return dict(base, reason='flat')
    R = bone_rotation(ibm)
    samples, nfb = [], 0
    for p in picks:
        v = int(cloud[p])
        nl = surf['N'][v] @ R.T if surf['good'][v] else np.zeros(3)
        ln = float(np.linalg.norm(nl))
        if ln < 1e-9:                               # no incident triangle / degenerate normal
            nfb += 1
            nl = local[p].copy()
            ln = float(np.linalg.norm(nl))
            if ln < 1e-9:                           # sample sits ON the bone origin
                nl, ln = np.array([0.0, 1.0, 0.0]), 1.0
        nl = nl / ln
        samples.append((float(local[p][0]), float(local[p][1]), float(local[p][2]),
                        float(nl[0]), float(nl[1]), float(nl[2])))
    return dict(samples=samples, nfallback=nfb, ndropped=ndrop, reason=None,
                maxoff=float(np.max(np.linalg.norm(P, axis=1))), maxoff_raw=maxoff_raw)


def model_bsurf(geo, chain_joint_names):
    """-> (lines, stats) for one model.  A BODY bone is any bone with >= MIN_CLOUD dominant
    vertices that is NOT itself a chain link of this model (those already have `ms` records).
    Ownership is c6.bone_clouds' DOMINANT rule — every vertex belongs to exactly one bone — so
    the two datasets describe the same partition of the mesh."""
    st = dict(bones=0, samples=0, nfallback=0, maxoff=0.0, maxoff_bone='',
              maxoff_raw=0.0, maxoff_raw_bone='', dropped=0, dropped_bones=[],
              skipped_flat=0, skipped_stray=0, candidates=0, cloud_verts=0, scaled=0,
              nonuniform=0, nonuniform_max=1.0, mirrored=0, ntri=0, caps={},
              extent=float(np.ptp(geo['V'], axis=0).max()))
    surf = load_surface(geo)
    if surf is None:
        return [], st
    st['ntri'] = surf['ntri']
    clouds = c6.bone_clouds(geo)
    kids = [[] for _ in range(len(geo['names']))]
    for c, p in enumerate(geo['parent']):
        if p is not None and 0 <= p < len(kids):
            kids[p].append(c)
    lines = []
    for j, name in enumerate(geo['names']):         # rig order: deterministic
        if name in chain_joint_names:
            continue
        cloud = np.unique(clouds[j])
        if len(cloud) < MIN_CLOUD or not np.all(np.isfinite(geo['P'][j])):
            continue
        st['candidates'] += 1
        st['cloud_verts'] += int(len(cloud))
        sv = np.linalg.svd(geo['ibms'][j][:3, :3], compute_uv=False)
        if not (0.99 <= sv.min() and sv.max() <= 1.01):
            st['scaled'] += 1
        ratio = float(sv.max() / max(sv.min(), 1e-12))
        if ratio > 1.01:
            st['nonuniform'] += 1
            st['nonuniform_max'] = max(st['nonuniform_max'], ratio)
        if np.linalg.det(geo['ibms'][j][:3, :3]) < 0:
            st['mirrored'] += 1
        span = bone_span(geo, kids, j)
        cap = max(BSURF_SPAN_K * span, BSURF_MIN_CAP)
        r = bone_surface(geo, surf, cloud, j, cap)
        if r['maxoff_raw'] > st['maxoff_raw']:
            st['maxoff_raw'], st['maxoff_raw_bone'] = r['maxoff_raw'], name
        if r['ndropped']:
            st['dropped'] += r['ndropped']
            st['dropped_bones'].append((name, r['ndropped'], len(cloud), r['maxoff_raw'],
                                        span, cap))
        if not r['samples']:
            st['skipped_stray' if r['reason'] == 'stray' else 'skipped_flat'] += 1
            continue
        lines.append('bs %s %d %s' % (name, len(r['samples']), ' '.join(
            '%.1f %.1f %.1f %.4f %.4f %.4f' % s for s in r['samples'])))
        st['caps'][name] = cap
        st['bones'] += 1
        st['samples'] += len(r['samples'])
        st['nfallback'] += r['nfallback']
        if r['maxoff'] > st['maxoff']:
            st['maxoff'], st['maxoff_bone'] = r['maxoff'], name
    return lines, st


def merge_bsurf(path, bs_by_model):
    """--bsurf-only: rewrite ONLY the `bs` records of an existing physics_mesh.txt.  Every `ms`
    record and every model header is carried across byte for byte, which is what makes the
    regeneration cheap and non-destructive.  The leading comment block is replaced by HEADER so
    that the grammar documented at the top of the file cannot drift from the code that writes
    it — the two modes then produce byte-identical files."""
    old = open(path).read().split('\n')
    out, cur = [], None
    lead = 0
    while lead < len(old) and old[lead].startswith('#'):
        lead += 1
    out.extend(HEADER)
    for ln in old[lead:]:
        if ln.startswith('bs '):
            continue
        if ln.startswith('model '):
            if cur is not None:
                out.extend(bs_by_model.get(cur, []))
            cur = ln[len('model '):].strip()
        out.append(ln)
    if cur is not None:                             # trailing model section
        while out and out[-1] == '':
            out.pop()
        out.extend(bs_by_model.get(cur, []))
        out.append('')
    return '\n'.join(out)


def verify_bsurf_file(path, caps=None):
    """Read the WRITTEN file back and check every `bs` record physically: field count, unit
    normals, offsets inside that bone's OWN span-relative cap, and offsets inside the MODEL'S
    OWN extent (a sample cannot sit further from its bone than the whole model is wide).
    `caps` is {model line -> dict(caps={bone: cap}, extent=float)}.  A check on the artifact,
    not on the variables that produced it — the artifact is what the runtime loads."""
    bad_len, bad_norm, bad_off, bad_abs, n_rec, n_smp = 0, 0, 0, 0, 0, 0
    worst_n, worst_p, worst_p_where = 0.0, 0.0, ''
    cur, info = '', {}
    for ln in open(path):
        if ln.startswith('model '):
            cur = ln[len('model '):].strip()
            info = (caps or {}).get(cur, {})
            continue
        if not ln.startswith('bs '):
            continue
        t = ln.split()
        n_rec += 1
        cap = info.get('caps', {}).get(t[1], CHAR_UNITS)
        extent = info.get('extent', CHAR_UNITS)
        try:
            n = int(t[2])
        except (IndexError, ValueError):
            bad_len += 1
            continue
        vals = [float(x) for x in t[3:]]
        if n < 1 or len(vals) != 6 * n:
            bad_len += 1
            continue
        n_smp += n
        for i in range(n):
            p = np.array(vals[6 * i:6 * i + 3])
            nv = np.array(vals[6 * i + 3:6 * i + 6])
            ln_ = float(np.linalg.norm(nv))
            mp = float(np.linalg.norm(p))
            worst_n = max(worst_n, abs(ln_ - 1.0))
            if mp > worst_p:
                worst_p, worst_p_where = mp, '%s %s' % (cur.split()[0] if cur else '?', t[1])
            if abs(ln_ - 1.0) > 1e-3:
                bad_norm += 1
            if mp > cap + 0.2:
                bad_off += 1
            if mp > extent:
                bad_abs += 1
    return dict(records=n_rec, samples=n_smp, bad_len=bad_len, bad_norm=bad_norm,
                bad_off=bad_off, bad_abs=bad_abs, worst_norm_err=worst_n,
                worst_off=worst_p, worst_off_where=worst_p_where)


def print_bsurf(bs_stats, total_bs, total_bs_samples, total_bs_fallback, total_bs_dropped,
                caps):
    top = sorted(bs_stats, key=lambda ms: -ms[1]['maxoff'])[:1]
    verts = sum(s['cloud_verts'] for _, s in bs_stats)
    print('bs: %d bones, %d samples, %d fallback normals, over %d models' %
          (total_bs, total_bs_samples, total_bs_fallback, len(bs_stats)))
    print('    stray cap max(%.1f * bone span, %.0f): %d of %d body-bone vertices dropped '
          '(%.2f%%)' % (BSURF_SPAN_K, BSURF_MIN_CAP, total_bs_dropped, verts,
                        100.0 * total_bs_dropped / max(verts, 1)))
    for m, s in top:
        print('    max |p| emitted: %.1f on %s %s' % (s['maxoff'], m, s['maxoff_bone']))
    v = verify_bsurf_file(OUT_MESH, caps)
    print('    artifact check: %d bs records / %d samples, malformed=%d non-unit normals=%d '
          '(worst |n|-1 = %.2e) over-own-bone-cap=%d over-model-extent=%d '
          '(worst |p| = %.1f on %s)'
          % (v['records'], v['samples'], v['bad_len'], v['bad_norm'], v['worst_norm_err'],
             v['bad_off'], v['bad_abs'], v['worst_off'], v['worst_off_where']))


def bsurf_problems(bs_stats, total_bs, total_bs_samples, caps, as_list=False):
    """gates on the BODY SURFACE half.  Every one of them can fail on real data."""
    problems = []
    if total_bs < 1:
        problems.append('bs lines %d — the body surface half produced nothing' % total_bs)
    if total_bs_samples < 4 * max(total_bs, 1):
        problems.append('bs samples %d for %d bones — under 4 per bone the "surface" is a '
                        'handful of points' % (total_bs_samples, total_bs))
    for want in ('keira-hd',):
        got = [s for m, s in bs_stats if m == want]
        if not got or got[0]['bones'] < 1:
            problems.append('%s produced 0 bs bones (the delivery model, SPEC §18)' % want)
    v = verify_bsurf_file(OUT_MESH, caps)
    if v['bad_len']:
        problems.append('%d malformed bs records in the written file' % v['bad_len'])
    if v['bad_norm']:
        problems.append('%d bs samples whose normal is not unit (worst |n|-1 = %.2e)'
                        % (v['bad_norm'], v['worst_norm_err']))
    if v['bad_off']:
        problems.append('%d bs samples beyond their own bone cap (worst %.1f on %s) — stray '
                        'weights reached the file'
                        % (v['bad_off'], v['worst_off'], v['worst_off_where']))
    if v['bad_abs']:
        problems.append('%d bs samples further from their own bone than their model is wide '
                        '(worst %.1f on %s)'
                        % (v['bad_abs'], v['worst_off'], v['worst_off_where']))
    if as_list:
        return problems
    if problems:
        print('VALIDATION FAILED:')
        for p in problems:
            print('  ' + p)
        return 1
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--bsurf-only', action='store_true',
                    help='regenerate only the `bs` body-surface records, leaving every `ms` '
                         'record and every other line of physics_mesh.txt byte-identical')
    args = ap.parse_args()
    bsurf_only = args.bsurf_only
    lines, sections = c6.parse_chains_file(CHAINS)
    mesh_out = list(HEADER)
    bs_by_model = {}         # 'alias alias' -> [bs lines]   (for --bsurf-only merging)
    bs_caps = {}             # 'alias alias' -> {bone -> that bone's stray cap}
    bs_stats = []            # (model, stats dict)
    rep = []
    failed_models = []       # (model, reason)
    empty_links = []         # (model, chain, link, joint name)
    total_ms = 0
    models_processed = 0     # alias names of sections whose geometry loaded
    per_chain_samples = {}   # (model, chain) -> total samples
    per_chain_extents = {}   # (model, chain) -> list of (rad, perp_max, axial_over)

    for sec in sections:
        model = sec.names[0]
        geo, err = None, None
        for nm in sec.names:
            try:
                geo = load_geometry_ibm(nm)
            except Exception as e:  # noqa: BLE001 — recorded, never silently skipped
                err = '%s: %s' % (type(e).__name__, e)
                geo = None
            if geo is not None:
                break
        if geo is None:
            failed_models.append((model, err or 'no GLB found (hd_anim k2e / '
                                                'decompiler_out levels)'))
            continue
        models_processed += len(sec.names)
        nmap = {n: i for i, n in enumerate(geo['names'])}
        mesh_out.append('model ' + ' '.join(sec.names))
        for ch in (() if bsurf_only else sec.chains):     # --bsurf-only never touches `ms`
            idx = [nmap.get(jn) for _, jn in ch.joints]
            rads = link_radii_from_chain(ch, len(idx))
            key = (model, ch.name)
            per_chain_samples.setdefault(key, 0)
            per_chain_extents.setdefault(key, [])
            for li, (j, (_, jname)) in enumerate(zip(idx, ch.joints)):
                if j is None or not np.all(np.isfinite(geo['P'][j])):
                    empty_links.append((model, ch.name, li,
                                        jname + ' (joint not in rig)'))
                    continue
                r = process_link(geo, j, li, idx if all(
                    x is not None for x in idx) else
                    [x if x is not None else j for x in idx], rads[li])
                if r['nverts'] == 0:
                    empty_links.append((model, ch.name, li, jname))
                rep.append('%s %s %d radii_p25=%.0f mesh_perp_max=%.1f '
                           'mesh_axial_over=%.1f nverts=%d nsamples=%d'
                           % (model, ch.name, li, rads[li], r['perp_max'],
                              r['axial_over'], r['nverts'], len(r['samples'])))
                per_chain_samples[key] += len(r['samples'])
                per_chain_extents[key].append((rads[li], r['perp_max'],
                                               r['axial_over']))
                if r['samples']:
                    total_ms += 1
                    mesh_out.append('ms %s %d %d %s' % (
                        ch.name, li, len(r['samples']),
                        ' '.join('%.1f %.1f %.1f' % s for s in r['samples'])))
            ext = per_chain_extents[key]
            if ext:
                rep.append('SUMMARY %s %s linkrad_min=%.0f linkrad_max=%.0f '
                           'meshext_min=%.1f meshext_max=%.1f'
                           % (model, ch.name,
                              min(e[0] for e in ext), max(e[0] for e in ext),
                              min(max(e[1], e[2]) for e in ext),
                              max(max(e[1], e[2]) for e in ext)))

        # ---- (SPEC §18) the BODY side: real surface samples for every non-chain bone ----
        chain_joint_names = set(jn for ch in sec.chains for _, jn in ch.joints)
        bsl, bst = model_bsurf(geo, chain_joint_names)
        bs_by_model[' '.join(sec.names)] = bsl
        bs_caps[' '.join(sec.names)] = dict(caps=bst['caps'], extent=bst['extent'])
        bs_stats.append((model, bst))
        mesh_out.extend(bsl)

    total_bs = sum(s['bones'] for _, s in bs_stats)
    total_bs_samples = sum(s['samples'] for _, s in bs_stats)
    total_bs_fallback = sum(s['nfallback'] for _, s in bs_stats)
    total_bs_dropped = sum(s['dropped'] for _, s in bs_stats)

    # ---- write outputs ----
    os.makedirs(os.path.dirname(OUT_REPORT), exist_ok=True)
    if bsurf_only:
        # only the `bs` lines change; `ms` and every comment survive byte for byte, and the
        # cycle-14 ms audit on disk stays valid because it was not recomputed.
        merged = merge_bsurf(OUT_MESH, bs_by_model)
        with open(OUT_MESH, 'w') as f:
            f.write(merged)
    else:
        with open(OUT_MESH, 'w') as f:
            f.write('\n'.join(mesh_out) + '\n')
    if bsurf_only:
        print('--bsurf-only: %s rewritten (bs records only), %s left untouched'
              % (OUT_MESH, OUT_REPORT))
        print_bsurf(bs_stats, total_bs, total_bs_samples, total_bs_fallback,
                    total_bs_dropped, bs_caps)
        return bsurf_problems(bs_stats, total_bs, total_bs_samples, bs_caps)
    with open(OUT_REPORT, 'w') as f:
        f.write('MESH EXTENTS AUDIT (cycle 14) — per chain link: the link radius the\n'
                'runtime already tests vs the measured extent of the skinned mesh the\n'
                'link actually carries. units: game units (4096 = 1 m).\n\n')
        f.write('\n'.join(rep) + '\n')
        f.write('\nmodels processed (alias names): %d\n' % models_processed)
        f.write('ms lines emitted: %d\n' % total_ms)
        f.write('\nMODELS WITH NO GEOMETRY (%d):\n' % len(failed_models))
        for m, why in failed_models:
            f.write('  %s — %s\n' % (m, why))
        f.write('\nLINKS WITH EMPTY CLOUD (%d):\n' % len(empty_links))
        for m, cn, li, jn in empty_links:
            f.write('  %s %s link %d joint %s\n' % (m, cn, li, jn))
        f.write('\n\nBODY SURFACE AUDIT (SPEC §18) — per model: the non-chain bones that got\n'
                '`bs` records (surface samples + outward normals, bone-local bind space).\n'
                'A sample is an OFFSET FROM ITS OWN BONE, so |p| is a distance from that bone,\n'
                'and a bone carries flesh along its own LENGTH: the stray cap is therefore\n'
                'max(%.1f * span, %.0f) with span = max(|bone-parent|, max|bone-child|), NOT a\n'
                'flat number (a flat 2048 dropped 18.53%% of all body vertices, including 77 of\n'
                'the 109 vertices of the mayor\'s chest — a hole generator, not a filter).\n'
                'Samples are written in FARTHEST-POINT ORDER: a runtime prefix of k of the %d\n'
                'is a valid near-optimal k-point subset.\n\n'
                % (BSURF_SPAN_K, BSURF_MIN_CAP, BSURF_MAX))
        for m, s in bs_stats:
            f.write('%s bones=%d/%d samples=%d tris=%d fallback_normals=%d '
                    'dropped=%d/%d(%.2f%%) skipped_stray=%d skipped_flat=%d max|p|=%.1f(%s) '
                    'max|p|_before_cap=%.1f(%s) scaled_ibm=%d nonuniform_ibm=%d(x%.3f) '
                    'mirrored_ibm=%d\n'
                    % (m, s['bones'], s['candidates'], s['samples'], s['ntri'],
                       s['nfallback'], s['dropped'], s['cloud_verts'],
                       100.0 * s['dropped'] / max(s['cloud_verts'], 1),
                       s['skipped_stray'], s['skipped_flat'],
                       s['maxoff'], s['maxoff_bone'] or '-', s['maxoff_raw'],
                       s['maxoff_raw_bone'] or '-', s['scaled'], s['nonuniform'],
                       s['nonuniform_max'], s['mirrored']))
        verts = sum(s['cloud_verts'] for _, s in bs_stats)
        f.write('\nbs lines: %d   samples: %d   fallback normals: %d   '
                'vertices dropped as stray: %d/%d (%.2f%%)\n'
                % (total_bs, total_bs_samples, total_bs_fallback, total_bs_dropped, verts,
                   100.0 * total_bs_dropped / max(verts, 1)))
        f.write('\nBONES THAT LOST VERTICES TO THE CAP '
                '(model bone dropped/cloud max|p| span cap):\n')
        for m, s in bs_stats:
            for nm_, nd, ncl, mx, sp, cp in s['dropped_bones']:
                f.write('  %s %s %d/%d %.1f span=%.1f cap=%.1f\n'
                        % (m, nm_, nd, ncl, mx, sp, cp))

    print_bsurf(bs_stats, total_bs, total_bs_samples, total_bs_fallback, total_bs_dropped,
                bs_caps)

    # ---- validation: fail loudly, never a vacuous zero ----
    problems = bsurf_problems(bs_stats, total_bs, total_bs_samples, bs_caps, as_list=True)
    if models_processed < 50:
        problems.append('models processed %d < 50' % models_processed)
    if total_ms < 300:
        problems.append('ms lines %d < 300' % total_ms)
    for cn in ('chestR', 'chestL'):
        if per_chain_samples.get(('keira-hd', cn), 0) < 1:
            problems.append('keira-hd %s produced 0 samples' % cn)
    for cn in ('tieL', 'tieR'):
        key = ('mayor-lod0', cn)
        if per_chain_samples.get(key, 0) < 1:
            problems.append('mayor-lod0 %s produced 0 samples' % cn)
            continue
        ext = per_chain_extents.get(key, [])
        if not any(p > r or a > r for r, p, a in ext):
            problems.append(
                'mayor-lod0 %s: no link with mesh extent beyond its radius — measured '
                '%s' % (cn, '; '.join('link%d rad=%.0f perp=%.1f axial=%.1f'
                                      % (i, r, p, a)
                                      for i, (r, p, a) in enumerate(ext))))
    if problems:
        print('VALIDATION FAILED:')
        for p in problems:
            print('  ' + p)
        print('outputs written anyway for inspection: %s , %s'
              % (OUT_MESH, OUT_REPORT))
        return 1

    print('OK: %d alias models across %d sections, %d ms lines, %d bs lines, %d failed '
          'models, %d empty-cloud links' % (models_processed,
                                            len(sections) - len(failed_models),
                                            total_ms, total_bs, len(failed_models),
                                            len(empty_links)))
    print('wrote %s (%d bytes)' % (OUT_MESH, os.path.getsize(OUT_MESH)))
    print('wrote %s (%d bytes)' % (OUT_REPORT, os.path.getsize(OUT_REPORT)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
