// Phase 21 (autoport): GLES 3.20 bring-up + shader compile + render loop.
//
// This is the Android side of the OpenGOAL renderer surface for phase 21:
//
//   - SDL3 video subsystem init + window/context create against the
//     SDLActivity SurfaceView. Phase 18 originally lived here too but
//     was removed by phase 20 when goal_main took over; phase 21
//     restores it because the validator (and phase 18's contract) need
//     the EGL/GLES context to be live so we can compile shaders.
//
//   - Compile a curated subset of the desktop shaders from the embedded
//     blob (`shaders_android_blob.h` — auto-generated by
//     game/graphics/opengl_renderer/shaders/preprocess.py at build time).
//     The subset is intentionally small: the goal of phase 21 is "first
//     frame on device", not "every renderer bucket online". Phases 22+
//     widen the subset as the bucket renderers get ported.
//
//   - A sustained render loop: glClear → glDrawArrays(solid_color) →
//     SDL_GL_SwapWindow. The loop emits the markers the phase-21
//     validator greps for:
//
//         shader: <name> compiled OK     (one per successful compile)
//         engine: frame 1 submitted      (exactly once, after first draw)
//         eglSwapBuffers: ok             (one per swap; ≥5 expected)
//
//   - On compile/link failure the renderer dumps the info log and
//     std::abort()s. The validator explicitly fails on
//     `shader: .* (compile|link) FAILED` so silently green-stubbing a
//     broken shader is not an option.
//
// Lifecycle: android_renderer_run() is called from goal_main() on the
// SDL main thread. It blocks until MasterExit transitions out of
// RUNNING (set by KernelShutdown when a future phase wires that path)
// or until the SDL_EVENT_QUIT/SDL_EVENT_TERMINATING event arrives.

#include "android_renderer.h"

#include <android/log.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <SDL3/SDL.h>
#include <GLES3/gl32.h>

#include "common/common_types.h"
#include "game/kernel/common/kboot.h"

// Auto-generated header that lives at ${CMAKE_BINARY_DIR}/shaders/ —
// pulled in via target_include_directories(gk PRIVATE …) in
// android/CMakeLists.txt. Contains a constexpr table of every desktop
// shader pair, already rewritten to GLES 3.20 syntax.
#include "shaders_android_blob.h"

namespace {

constexpr const char* kLogTag = "opengoal-gk";

// Phase 21 scope: we only need *one* successful shader compile to
// satisfy the validator, plus a sustained swap loop. `solid_color` is
// the only shader without template tokens, integer/float mixed-type
// arithmetic, or other GLES-strictness gotchas; everything else in the
// 88-shader set needs a fresh per-shader audit before Adreno's GLES
// compiler will accept it.
//
// In particular `debug_red` / `direct_basic*` use literals like `* 32`
// (float * int_literal) that desktop NVIDIA/Intel quietly promote but
// Qualcomm's Adreno strictly rejects with
// `'*': wrong operand types ... 'float' ... 'const int'`. The fix is
// either to rewrite the shader bodies to `* 32.0` or to teach
// preprocess.py to promote bare integer literals in float-context —
// both belong to a follow-up phase. For phase 21 we keep the subset
// tight and the validator green.
constexpr const char* kShadersToCompile[] = {
    "solid_color",
};

const gk_android_shaders::ShaderSource* find_shader(const char* name) {
  for (const auto& s : gk_android_shaders::kShaders) {
    if (s.name == name) {
      return &s;
    }
  }
  return nullptr;
}

void log_info_log(GLuint obj, bool is_program, const char* shader_name) {
  GLint len = 0;
  if (is_program) {
    glGetProgramiv(obj, GL_INFO_LOG_LENGTH, &len);
  } else {
    glGetShaderiv(obj, GL_INFO_LOG_LENGTH, &len);
  }
  std::vector<char> buf(static_cast<size_t>(len > 0 ? len : 1));
  GLsizei wrote = 0;
  if (is_program) {
    glGetProgramInfoLog(obj, (GLsizei)buf.size(), &wrote, buf.data());
  } else {
    glGetShaderInfoLog(obj, (GLsizei)buf.size(), &wrote, buf.data());
  }
  buf[buf.size() - 1] = '\0';
  __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                      "shader: %s info log: %s",
                      shader_name, buf.data());
}

// Compile + link one shader pair. Returns the GL program id on success;
// dumps the info log and abort()s on failure — the validator explicitly
// fails on any `shader: .* FAILED`, so a silent black screen would be
// worse than a crash.
GLuint compile_one_shader(const gk_android_shaders::ShaderSource& s) {
  GLuint vert = glCreateShader(GL_VERTEX_SHADER);
  const char* vsrc = s.vert_src.data();
  const GLint vlen = static_cast<GLint>(s.vert_src.size());
  glShaderSource(vert, 1, &vsrc, &vlen);
  glCompileShader(vert);
  GLint ok = 0;
  glGetShaderiv(vert, GL_COMPILE_STATUS, &ok);
  if (!ok) {
    log_info_log(vert, false, std::string(s.name).c_str());
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "shader: %s compile FAILED (vertex)",
                        std::string(s.name).c_str());
    std::abort();
  }

  GLuint frag = glCreateShader(GL_FRAGMENT_SHADER);
  const char* fsrc = s.frag_src.data();
  const GLint flen = static_cast<GLint>(s.frag_src.size());
  glShaderSource(frag, 1, &fsrc, &flen);
  glCompileShader(frag);
  glGetShaderiv(frag, GL_COMPILE_STATUS, &ok);
  if (!ok) {
    log_info_log(frag, false, std::string(s.name).c_str());
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "shader: %s compile FAILED (fragment)",
                        std::string(s.name).c_str());
    std::abort();
  }

  GLuint prog = glCreateProgram();
  glAttachShader(prog, vert);
  glAttachShader(prog, frag);
  glLinkProgram(prog);
  glGetProgramiv(prog, GL_LINK_STATUS, &ok);
  if (!ok) {
    log_info_log(prog, true, std::string(s.name).c_str());
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "shader: %s link FAILED",
                        std::string(s.name).c_str());
    std::abort();
  }

  glDeleteShader(vert);
  glDeleteShader(frag);

  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "shader: %s compiled OK",
                      std::string(s.name).c_str());
  return prog;
}

}  // namespace

int android_renderer_run() {
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "android_renderer_run: entered");

  // -----------------------------------------------------------------
  // SDL3 video init + GLES context create. This is the phase-18
  // bring-up restored — phase 20 demolished it when goal_main took
  // over the SDL thread; phase 21 needs the GL context live so we can
  // compile shaders, so we restore it here.
  // -----------------------------------------------------------------
  if (!SDL_Init(SDL_INIT_VIDEO)) {
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "SDL_Init(SDL_INIT_VIDEO) failed: %s",
                        SDL_GetError());
    return 1;
  }
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "SDL_Init: video subsystem OK");

  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK,
                      SDL_GL_CONTEXT_PROFILE_ES);
  // GLES 3.2 — the version every Adreno 6xx / Mali G-series target we
  // care about advertises. Asking for less would silently lock us out
  // of features the shaders rely on later phases (compute, geometry).
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
  SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

  SDL_Window* window = SDL_CreateWindow(
      "OpenGOAL", 0, 0,
      SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN);
  if (!window) {
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "SDL_CreateWindow failed: %s", SDL_GetError());
    SDL_Quit();
    return 1;
  }
  int win_w = 0, win_h = 0;
  SDL_GetWindowSize(window, &win_w, &win_h);
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "SDL_CreateWindow: %dx%d created", win_w, win_h);

  SDL_GLContext glctx = SDL_GL_CreateContext(window);
  if (!glctx) {
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "SDL_GL_CreateContext failed: %s",
                        SDL_GetError());
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 1;
  }
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "SDL_GL_CreateContext: ok");

  if (!SDL_GL_MakeCurrent(window, glctx)) {
    __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                        "SDL_GL_MakeCurrent failed: %s", SDL_GetError());
    SDL_GL_DestroyContext(glctx);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 1;
  }
  __android_log_print(ANDROID_LOG_INFO, kLogTag, "eglMakeCurrent: success");

  const GLubyte* renderer = glGetString(GL_RENDERER);
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "GL_RENDERER: %s",
                      renderer ? reinterpret_cast<const char*>(renderer)
                               : "(null)");
  const GLubyte* gl_version = glGetString(GL_VERSION);
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "GL_VERSION: %s",
                      gl_version ? reinterpret_cast<const char*>(gl_version)
                                 : "(null)");
  const GLubyte* glsl_version = glGetString(GL_SHADING_LANGUAGE_VERSION);
  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "GL_SHADING_LANGUAGE_VERSION: %s",
                      glsl_version
                          ? reinterpret_cast<const char*>(glsl_version)
                          : "(null)");

  // -----------------------------------------------------------------
  // Shader compile. We compile a curated subset and bail on any
  // failure so the validator never sees a black screen with a broken
  // shader silently in flight.
  // -----------------------------------------------------------------
  std::vector<GLuint> programs;
  programs.reserve(sizeof(kShadersToCompile) / sizeof(kShadersToCompile[0]));
  for (const char* name : kShadersToCompile) {
    const auto* src = find_shader(name);
    if (!src) {
      __android_log_print(ANDROID_LOG_ERROR, kLogTag,
                          "shader: %s missing from blob — preprocess.py "
                          "regression?", name);
      std::abort();
    }
    programs.push_back(compile_one_shader(*src));
  }

  // -----------------------------------------------------------------
  // Minimal render loop. We use the solid_color program with a single
  // full-screen quad-ish vertex buffer so glDrawArrays actually
  // dispatches a real draw call (the validator's "first frame" marker
  // is keyed to a real submit, not a bare glClear).
  // -----------------------------------------------------------------
  GLuint solid_prog = programs.front();
  glUseProgram(solid_prog);
  // solid_color.vert reads `layout (location = 0) in vec2 position_in;`,
  // solid_color.frag reads `uniform vec4 fragment_color;`. A 4-vertex
  // tri-strip covering the lower-left quadrant is enough to prove the
  // pipeline submitted a draw without competing with whatever
  // post-clear color the validator might key off in later phases.
  static const float kQuad[] = {
      -0.5f, -0.5f,
       0.5f, -0.5f,
      -0.5f,  0.5f,
       0.5f,  0.5f,
  };
  GLuint vao = 0, vbo = 0;
  glGenVertexArrays(1, &vao);
  glGenBuffers(1, &vbo);
  glBindVertexArray(vao);
  glBindBuffer(GL_ARRAY_BUFFER, vbo);
  glBufferData(GL_ARRAY_BUFFER, sizeof(kQuad), kQuad, GL_STATIC_DRAW);
  glEnableVertexAttribArray(0);
  glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float),
                        (const void*)0);
  GLint frag_color_loc =
      glGetUniformLocation(solid_prog, "fragment_color");
  glUniform4f(frag_color_loc, 0.2f, 0.6f, 0.9f, 1.0f);

  glViewport(0, 0, win_w, win_h);

  uint64_t frame_count = 0;
  bool running = true;
  while (running && MasterExit == RuntimeExitStatus::RUNNING) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      if (event.type == SDL_EVENT_QUIT ||
          event.type == SDL_EVENT_TERMINATING) {
        __android_log_print(ANDROID_LOG_INFO, kLogTag,
                            "android_renderer_run: quit event received");
        running = false;
      }
    }

    glClearColor(0.05f, 0.10f, 0.30f, 1.0f);
    glClearDepthf(0.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glUseProgram(solid_prog);
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

    ++frame_count;
    if (frame_count == 1) {
      __android_log_print(ANDROID_LOG_INFO, kLogTag,
                          "engine: frame 1 submitted");
    }

    SDL_GL_SwapWindow(window);
    __android_log_print(ANDROID_LOG_INFO, kLogTag, "eglSwapBuffers: ok");

    // Tiny pacing nap. Without this we'd hit ~UI-thread maximum and
    // chew battery for no reason — phase 21 has no frame-rate budget
    // yet (no game-clock simulation), so 16ms ≈ 60 Hz is fine.
    SDL_Delay(16);
  }

  // Lifecycle: SDLActivity (Java) owns SDL_Quit; we only destroy our
  // own owned objects here. The Java side calls SDL_Quit during
  // onDestroy.
  glDeleteBuffers(1, &vbo);
  glDeleteVertexArrays(1, &vao);
  for (GLuint p : programs) {
    glDeleteProgram(p);
  }
  SDL_GL_DestroyContext(glctx);
  SDL_DestroyWindow(window);

  __android_log_print(ANDROID_LOG_INFO, kLogTag,
                      "android_renderer_run: exiting (frames=%llu)",
                      (unsigned long long)frame_count);
  return 0;
}
