#!/usr/bin/env bash
# Phase Gpkg-distributable (autoport 2026-06-27): build the COMPRESSED
# runtime-asset bundle shipped inside the APK.
#
# The PC pipeline (unchanged) extracts the jak1 runtime data into
#   android/app/src/<game>/assets/iso_data/<game>/   (CGO/DGO/STR/VAG/... )
#   android/app/src/<game>/assets/fr3/               (GAME/intro/title fr3)
# This script packs that whole set into ONE DEFLATE zip
#   android/app/src/<game>/assets-bundled/bundle/<game>_assets.zip
# plus a small manifest
#   android/app/src/<game>/assets-bundled/bundle/manifest.properties
# that the on-device LoaderActivity reads to: size the determinate progress
# bar, pre-check free storage, and verify the unpack (file count + bytes).
#
# Why a single compressed archive instead of the raw uncompressed dirs the
# APK used to bundle (noCompress cgo/str/vag/...): the raw layout shipped
# ~1.34 GiB verbatim and laid every file down at install. One compressed
# archive shrinks the APK and keeps the raw files off the device until the
# first-run decompress.
#
# Zip entry layout (LoaderActivity maps these to the on-device data root):
#   iso_data/<game>/*  -> <filesDir>/iso_data/<game>/*   (fakeiso data root)
#   fr3/*              -> <filesDir>/out/<game>/fr3/*     (renderer textures)
#
# Idempotent: regenerates only when the zip/manifest is missing or older
# than any raw input. goal_src is untouched — this is packaging only.
set -euo pipefail

GAME="${1:-jak1}"
# BUNDLE_VERSION bumps force a re-decompress on device (new APK). Keep it in
# lockstep with the APK's asset payload; bump when the extracted data changes.
VERSION="${BUNDLE_VERSION:-1}"

cd "$(cd "$(dirname "$0")" && pwd)"   # -> android/
ASSETS="app/src/${GAME}/assets"
ISO_SRC="${ASSETS}/iso_data/${GAME}"
FR3_SRC="${ASSETS}/fr3"
OUT_DIR="app/src/${GAME}/assets-bundled/bundle"
ZIP_REL="${OUT_DIR}/${GAME}_assets.zip"
MANIFEST="${OUT_DIR}/manifest.properties"
ZIP_ABS="$(pwd)/${ZIP_REL}"

[ -d "$ISO_SRC" ] || { echo "[asset-bundle] FATAL: no iso_data at $ISO_SRC (run the PC extract first)" >&2; exit 1; }

mkdir -p "$OUT_DIR"

# --- Staleness check: skip the (multi-minute) repack when already current. ---
if [ -f "$ZIP_REL" ] && [ -f "$MANIFEST" ]; then
  newest_src=$(find "$ISO_SRC" ${FR3_SRC:+"$FR3_SRC"} -type f -printf '%T@\n' 2>/dev/null | sort -rn | head -1 | cut -d. -f1)
  zip_mtime=$(stat -c %Y "$ZIP_REL")
  cur_ver=$(grep -E '^version=' "$MANIFEST" | cut -d= -f2 || echo "")
  if [ -n "$newest_src" ] && [ "$zip_mtime" -ge "$newest_src" ] && [ "$cur_ver" = "$VERSION" ]; then
    echo "[asset-bundle] up to date: $ZIP_REL (version=$VERSION)"
    exit 0
  fi
fi

echo "[asset-bundle] packing $GAME → $ZIP_REL (one-time; cached after)…"

# Raw totals BEFORE compression (manifest drives the progress bar + storage check).
RAW_BYTES=$(find "$ISO_SRC" ${FR3_SRC:+"$FR3_SRC"} -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')
FILE_COUNT=$(find "$ISO_SRC" ${FR3_SRC:+"$FR3_SRC"} -type f | wc -l | tr -d ' ')

rm -f "$ZIP_ABS"
# -6 = balanced DEFLATE (STR/VAG audio dominates and barely compresses, so a
# higher level buys little for a lot more time). -X drops extra metadata. -q
# quiet. Entry paths are relative to assets/, i.e. iso_data/<game>/* and fr3/*.
(
  cd "$ASSETS"
  if [ -d fr3 ]; then
    zip -r -6 -X -q "$ZIP_ABS" "iso_data/${GAME}" "fr3"
  else
    zip -r -6 -X -q "$ZIP_ABS" "iso_data/${GAME}"
  fi
)

ZIP_BYTES=$(stat -c %s "$ZIP_ABS")
RATIO=$(awk "BEGIN{ if($RAW_BYTES>0) printf \"%.1f\", 100.0*$ZIP_BYTES/$RAW_BYTES; else print \"0\" }")

cat > "$MANIFEST" <<EOF
# Generated by android/build_asset_bundle.sh — do not edit.
version=${VERSION}
game=${GAME}
file_count=${FILE_COUNT}
raw_bytes=${RAW_BYTES}
zip_bytes=${ZIP_BYTES}
EOF

echo "[asset-bundle] done: ${ZIP_REL}"
echo "[asset-bundle]   files=${FILE_COUNT}  raw=${RAW_BYTES}B  zip=${ZIP_BYTES}B  (${RATIO}% of raw)"
