#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <GLES3/gl3.h>
#include <fstream>
#include <iostream>
#include <vector>
#include <cstring>
#include <cmath>
#include <string>
#include <stdexcept>
void check(){auto e=glGetError(); if(e)throw std::runtime_error("GL error "+std::to_string(e));}
GLuint shader(GLenum type,std::string s){GLuint a=glCreateShader(type);const char*p=s.c_str();glShaderSource(a,1,&p,0);glCompileShader(a);GLint ok;glGetShaderiv(a,GL_COMPILE_STATUS,&ok);char l[16384];glGetShaderInfoLog(a,sizeof(l),0,l);if(!ok)throw std::runtime_error(l);return a;}
GLuint program(std::string path,bool probe){std::ifstream f(path);std::string s((std::istreambuf_iterator<char>(f)),{});GLuint p=glCreateProgram();glAttachShader(p,shader(GL_VERTEX_SHADER,s));glAttachShader(p,shader(GL_FRAGMENT_SHADER,"#version 300 es\nprecision highp float;out vec4 c;void main(){c=vec4(1);}"));const char* v[]={"gl_Position","probe_grass_pre","probe_grass_post","probe_grass_ids"};glTransformFeedbackVaryings(p,probe?4:1,v,GL_SEPARATE_ATTRIBS);glLinkProgram(p);GLint ok;glGetProgramiv(p,GL_LINK_STATUS,&ok);char l[8192];glGetProgramInfoLog(p,sizeof(l),0,l);if(!ok)throw std::runtime_error(l);return p;}
void uf(GLuint p,const char*n,float v){glUniform1f(glGetUniformLocation(p,n),v);}void ui(GLuint p,const char*n,int v){glUniform1i(glGetUniformLocation(p,n),v);}void uv(GLuint p,const char*n,float a,float b,float c,float d){glUniform4f(glGetUniformLocation(p,n),a,b,c,d);}
std::vector<float> run(GLuint p,bool probe,int contact,int wind,std::string file){
 glUseProgram(p);uf(p,"u_near_dist",100000);uf(p,"u_card_dist",200000);uf(p,"u_time",wind*3.7);uf(p,"u_droop_len",1);uf(p,"fog_constant",1);float camera[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};glUniformMatrix4fv(glGetUniformLocation(p,"camera"),1,0,camera);ui(p,"u_shrub_contact_on",contact);ui(p,"u_tie_contact_on",contact);ui(p,"u_shrub_native_on",wind);uf(p,"u_tie_sway_amp",wind*100.f);uf(p,"u_tie_sway_time",3.7f);uf(p,"u_tie_sway_flutter",.2f);glUniform2f(glGetUniformLocation(p,"u_tie_sway_dir"),.6f,.8f);uv(p,"u_jak_pos",0,0,0,contact);uv(p,"u_jak_ledge",100,0,100,contact);ui(p,"u_trample_count",contact);uv(p,"u_trample[0]",100,0,100,1000);uv(p,"u_trample2[0]",.7,0,0,0);
 ui(p,"tex_T18",0);ui(p,"u_tie_contact_tex",1);ui(p,"tex_T10",2);float mat[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};glUniformMatrix4fv(glGetUniformLocation(p,"cam_no_persp"),1,0,mat);uv(p,"persp0",0,0,1,.01);uv(p,"persp1",1,1,0,1);
 GLuint ub=glGetUniformBlockIndex(p,"ub_frame");if(ub!=GL_INVALID_INDEX)glUniformBlockBinding(p,ub,2);
 GLuint buffers[4];glGenBuffers(4,buffers);int widths[]={4,4,4,2};for(int i=0;i<(probe?4:1);i++){glBindBuffer(GL_TRANSFORM_FEEDBACK_BUFFER,buffers[i]);glBufferData(GL_TRANSFORM_FEEDBACK_BUFFER,10*widths[i]*4,nullptr,GL_STREAM_READ);glBindBufferBase(GL_TRANSFORM_FEEDBACK_BUFFER,i,buffers[i]);}
 GLuint q;glGenQueries(1,&q);glEnable(GL_RASTERIZER_DISCARD);glBeginQuery(GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN,q);glBeginTransformFeedback(GL_POINTS);glDrawArrays(GL_POINTS,0,10);glEndTransformFeedback();glEndQuery(GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN);glDisable(GL_RASTERIZER_DISCARD);GLuint count;glGetQueryObjectuiv(q,GL_QUERY_RESULT,&count);check();std::cout<<" primitives="<<count<<std::endl;if(count!=10)throw std::runtime_error("empty capture");std::vector<float> all;for(int i=0;i<(probe?4:1);i++){glBindBuffer(GL_TRANSFORM_FEEDBACK_BUFFER,buffers[i]);void* data=glMapBufferRange(GL_TRANSFORM_FEEDBACK_BUFFER,0,10*widths[i]*4,GL_MAP_READ_BIT);if(!data)throw std::runtime_error("map failed");auto old=all.size();all.resize(old+10*widths[i]);memcpy(all.data()+old,data,10*widths[i]*4);glUnmapBuffer(GL_TRANSFORM_FEEDBACK_BUFFER);}std::ofstream out(file,std::ios::binary);out.write((char*)all.data(),all.size()*4);glDeleteBuffers(4,buffers);glDeleteQueries(1,&q);check();return all;}
int main(int argc,char**argv){try{auto get=(PFNEGLGETPLATFORMDISPLAYEXTPROC)eglGetProcAddress("eglGetPlatformDisplayEXT");EGLDisplay d=get(EGL_PLATFORM_SURFACELESS_MESA,EGL_DEFAULT_DISPLAY,nullptr);EGLint major,minor;if(!eglInitialize(d,&major,&minor))throw std::runtime_error("eglInitialize failed "+std::to_string(eglGetError()));eglBindAPI(EGL_OPENGL_ES_API);EGLint a[]={EGL_SURFACE_TYPE,EGL_PBUFFER_BIT,EGL_RENDERABLE_TYPE,EGL_OPENGL_ES3_BIT,EGL_NONE};EGLConfig config;EGLint n;eglChooseConfig(d,a,&config,1,&n);EGLint ca[]={EGL_CONTEXT_CLIENT_VERSION,3,EGL_NONE};auto ctx=eglCreateContext(d,config,EGL_NO_CONTEXT,ca);if(!eglMakeCurrent(d,EGL_NO_SURFACE,EGL_NO_SURFACE,ctx))throw std::runtime_error("eglMakeCurrent failed");EGLint pa[]={EGL_WIDTH,1,EGL_HEIGHT,1,EGL_NONE}; auto surf=eglCreatePbufferSurface(d,config,pa); eglMakeCurrent(d,surf,surf,ctx);std::cout<<"BANC_SYNTHETIQUE renderer="<<glGetString(GL_RENDERER)<<" version="<<glGetString(GL_VERSION)<<std::endl;
 GLuint vao;glGenVertexArrays(1,&vao);glBindVertexArray(vao);float pos[36];for(int i=0;i<12;i++){pos[i*3]=100+i*37;pos[i*3+1]=-200+i*170;pos[i*3+2]=150+i*29;}GLuint vb;glGenBuffers(1,&vb);glBindBuffer(GL_ARRAY_BUFFER,vb);glBufferData(GL_ARRAY_BUFFER,sizeof(pos),pos,GL_STATIC_DRAW);glVertexAttribPointer(0,3,GL_FLOAT,0,0,0);glEnableVertexAttribArray(0);glVertexAttribI4i(2,0,0,0,0);glVertexAttribI4i(3,0,0,0,0);glVertexAttrib4f(4,0,1,0,1);glVertexAttrib1f(7,.25);glVertexAttrib1f(8,.3);glVertexAttribI4i(9,1,0,0,0);glVertexAttribI4ui(10,1,0,0,0);
 float frame[56]={};for(int k=0;k<2;k++)for(int i=0;i<4;i++)frame[k*16+i*5]=1;frame[47]=1;GLuint ub;glGenBuffers(1,&ub);glBindBuffer(GL_UNIFORM_BUFFER,ub);glBufferData(GL_UNIFORM_BUFFER,sizeof(frame),frame,GL_STATIC_DRAW);glBindBufferBase(GL_UNIFORM_BUFFER,2,ub);
 GLuint tex[3];glGenTextures(3,tex);for(int t=0;t<3;t++){float data[24]={};for(int x=0;x<2;x++){int off=t==0?8+x*4:x*4;data[off]=100;data[off+1]=0;data[off+2]=150;data[off+3]=2000;if(t==0){data[x*4]=.04;data[x*4+1]=.02;data[x*4+2]=2000;data[x*4+3]=1;}}glActiveTexture(GL_TEXTURE0+t);glBindTexture(GL_TEXTURE_2D,tex[t]);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA32F,2,3,0,GL_RGBA,GL_FLOAT,data);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);}
 glDisableVertexAttribArray(0);glVertexAttrib4f(0,100,0,150,2000);glVertexAttrib4f(1,.3,.5,.2,.1);glVertexAttrib4f(2,.4,.5,.6,1e9);glVertexAttrib4f(3,.5,.5,.5,0);glVertexAttrib4f(4,0,1,0,0);
 GLuint p[2]={program(std::string(argv[1])+"/grass-0.vert",false),program(std::string(argv[1])+"/grass-1.vert",true)};
 for(int c=0;c<2;c++)for(int w=0;w<2;w++){std::string tag=std::string(argv[1])+"/grass-c"+std::to_string(c)+"-w"+std::to_string(w);auto a=run(p[0],false,c,w,tag+"-off.bin"),b=run(p[1],true,c,w,tag+"-on.bin");int changed=0;for(int i=0;i<10;i++){for(int j=0;j<12;j++)if(!std::isfinite(b[(j/4)*40+i*4+j%4]))throw std::runtime_error("nonfinite");uint32_t ids[2];memcpy(ids,&b[120+i*2],8);if(ids[0]!=0||ids[1]!=(unsigned)i)throw std::runtime_error("bad grass IDs");if(b[40+i*4+3]!=1||b[80+i*4+3]!=1)throw std::runtime_error("culled grass");if(memcmp(&b[40+i*4],&b[80+i*4],16))changed++;}bool equal=!memcmp(a.data(),b.data(),160);std::cout<<"grass contact="<<c<<" time="<<w<<" captured=10 position_bytes=160 equal="<<equal<<" pre_post_changed="<<changed<<std::endl;if(!equal || (c && !changed) || (!c && changed))throw std::runtime_error("grass neutrality/population mismatch");}

 return 0;}catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
