#!/usr/bin/env python3
"""
Phase B2 — per-CGO ELF wrapper builder.

Given a CGO file, enumerate every main-segment function across every v3
object record, concatenate the function bodies (16-byte aligned per
function) into a flat byte stream, and link them together with the
b2_harness.S static stub into a single static aarch64 ELF.

The resulting ELF runs under qemu-aarch64-static and takes one decimal
argv[1] in [0, fn_count) — that index is used by the harness to pick
the function to invoke.

Output layout per CGO:
   <build_dir>/<cgo>.functions.bin       raw concatenated bytes
   <build_dir>/<cgo>.offsets.bin         u32 per function, byte offset
                                         into functions.bin
   <build_dir>/<cgo>.data.S              data .S referencing the .bin's
   <build_dir>/<cgo>.data.o              assembled data
   <build_dir>/<cgo>.elf                 final linked ELF
   <build_dir>/<cgo>.fnnames.txt         one (object, fn-index) pair per
                                         line, in the same order as the
                                         function index — used by the
                                         driver to label failures

Re-running on the same CGO produces a byte-identical ELF (the harness
S and the python emitter are deterministic), so the driver's spot-check
gets a stable result.
"""

from __future__ import annotations

import os
import struct
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
LIB_DIR = REPO_ROOT / ".autoport" / "lib"

sys.path.insert(0, str(LIB_DIR))
from cgo_structure_check import parse_cgo, parse_object_bytes  # noqa: E402
from cgo_inspect import (  # noqa: E402
    parse_function_offsets,
    slice_function_body,
    ParseError,
)

ARM_AS = "aarch64-linux-gnu-as"
ARM_LD = "aarch64-linux-gnu-ld"
HARNESS_S = REPO_ROOT / "test" / "arm64" / "b2_harness.S"

FN_ALIGN = 16  # functions are 16-byte aligned in the wrapper ELF


def enumerate_functions(cgo_path: Path) -> list[tuple[str, int, bytes]]:
    """Walk every v3 object in the CGO, yield (obj_name, fn_index, body)
    for every main-segment function. The order matches the order
    objdump -D would emit if we treated the concatenated bodies as a
    single .text section.
    """
    records = parse_cgo(str(cgo_path))
    out: list[tuple[str, int, bytes]] = []
    for name, blob in records:
        parsed = parse_object_bytes(blob)
        if parsed is None:
            continue
        link_view, code_view = parsed
        try:
            tags = parse_function_offsets(link_view, code_view)
        except ParseError:
            continue
        for idx in range(len(tags)):
            try:
                body = slice_function_body(code_view, tags, idx)
            except ParseError:
                continue
            if not body:
                continue
            out.append((name, idx, body))
    return out


def build_elf(cgo_path: Path, build_dir: Path) -> tuple[Path, list[tuple[str, int, int]]]:
    """Build the per-CGO wrapper ELF. Returns (elf_path, fn_table)
    where fn_table is a list of (obj_name, fn_idx, body_len) entries in
    function-index order.
    """
    build_dir.mkdir(parents=True, exist_ok=True)
    cgo_name = cgo_path.name  # e.g. KERNEL.CGO
    stem = cgo_name.replace(".", "_")  # KERNEL_CGO

    fns = enumerate_functions(cgo_path)
    if not fns:
        raise RuntimeError(f"no functions in {cgo_path}")

    # Concatenate function bodies with 16-byte alignment.
    blob = bytearray()
    offsets: list[int] = []
    fn_table: list[tuple[str, int, int]] = []
    for obj_name, fn_idx, body in fns:
        # Pad to FN_ALIGN.
        pad = (-len(blob)) % FN_ALIGN
        if pad:
            blob.extend(b"\x00" * pad)
        offsets.append(len(blob))
        blob.extend(body)
        fn_table.append((obj_name, fn_idx, len(body)))

    # Trailing pad so the .incbin doesn't accidentally end on a
    # non-aligned boundary that could trip up subsequent sections.
    pad = (-len(blob)) % FN_ALIGN
    if pad:
        blob.extend(b"\x00" * pad)

    bin_fns = build_dir / f"{stem}.functions.bin"
    bin_offs = build_dir / f"{stem}.offsets.bin"
    bin_fns.write_bytes(bytes(blob))
    bin_offs.write_bytes(b"".join(struct.pack("<I", o) for o in offsets))

    # Generate the data .S referencing the two .bin files.
    data_s = build_dir / f"{stem}.data.S"
    data_s.write_text(
        f"""// auto-generated by b2_wrap_fn.py — do not edit
.section .rodata
.global fn_count
.type fn_count, %object
.align 4
fn_count:
    .word {len(offsets)}

.global fn_offsets
.type fn_offsets, %object
.align 4
fn_offsets:
    .incbin "{bin_offs}"

.section .text
.global fn_base
.type fn_base, %object
.align 4
fn_base:
    .incbin "{bin_fns}"
"""
    )

    harness_o = build_dir / f"{stem}.harness.o"
    data_o = build_dir / f"{stem}.data.o"
    elf = build_dir / f"{stem}.elf"

    subprocess.run(
        [ARM_AS, str(HARNESS_S), "-o", str(harness_o)],
        check=True, capture_output=True, text=True,
    )
    subprocess.run(
        [ARM_AS, str(data_s), "-o", str(data_o)],
        check=True, capture_output=True, text=True,
    )
    subprocess.run(
        [
            ARM_LD, str(harness_o), str(data_o),
            "-o", str(elf),
            "-e", "_start",
            "--no-warn-rwx-segments",
        ],
        check=True, capture_output=True, text=True,
    )

    # Write the fn-name table next to the ELF (one entry per index).
    names = build_dir / f"{stem}.fnnames.txt"
    with open(names, "w") as f:
        for obj_name, fn_idx, body_len in fn_table:
            f.write(f"{obj_name}\t{fn_idx}\t{body_len}\n")

    return elf, fn_table


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <cgo_path> <build_dir>", file=sys.stderr)
        return 2
    cgo = Path(sys.argv[1])
    out = Path(sys.argv[2])
    elf, table = build_elf(cgo, out)
    print(f"{elf}\t{len(table)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
