#!/usr/bin/env python3
"""LE MANIFESTE DU PACK EST UN PRODUIT DU BUILD — la garde, en UN seul endroit.

`android/build_cgo_pack.sh` et `android/build_custom_pack.sh` reecrivent
`android/app/src/<jeu>/assets-slim/bundle/<jeu>_{cgo,custom}.manifest.properties` a CHAQUE
empaquetage (leur en-tete le dit : « Generated by … — do not edit »). Ces fichiers etaient
pourtant SUIVIS par git : l'arbre devenait sale a chaque build, sans qu'une seule ligne de code
ait bouge. Ce que ca a coute, mesure les 18-19/09 : des commits de bruit, l'annonce « build
publie » qui prenait ce fichier pour du code de jeu, et surtout l'essai 5 de hud-eco-gauge —
porte VERTE sur l'appareil a 23:12 — JETE par la porte « arbre sale herite » pour ce seul
fichier.

LE POINT DE PRODUCTION, PAS LE POINT DE CONTROLE (DIRECTIVES/non-destruction). Le palliatif
etait une mise de cote dans `.commit_quarantine.json` : le fichier salissait toujours, on avait
juste arrete de le representer. La correction retire le fichier de l'index et pose une regle
`.gitignore` GENERIQUE : il ne peut plus salir, et un manifeste NEUF (un jeu de plus, un pack de
plus) naitra ignore sans que personne y pense.

CE QUE L'APK NE PERD PAS. Gradle prend le dossier `bundle/` en bloc ; le suivi git n'a aucune
prise sur ce qu'il empaquete. La preuve tient dans le frere du manifeste : `*_cgo.zip` et
`*_custom.zip` sont ignores depuis toujours (`.gitignore:170-171`) et partent dans chaque APK.

CE MODULE EST LA SOURCE UNIQUE DU VERDICT : la suite (`tests/harness/test_pack_manifest_is_generated.py`)
et le recensement (`lib/census/harness-pack-manifest-is-a-build-artefact.sh`) l'appellent tous
les deux, sur le depot LIVRE et sur des depots JETABLES semes par `semer()`.

MARQUEUR: pack-manifeste-produit-du-build-2026-09-20
"""
from __future__ import annotations

import subprocess
from pathlib import Path

# La regle `.gitignore` attendue. Un seul litteral, lu par la garde ET recopie dans `semer()` :
# le bras d'APRES du banc ne peut pas passer avec une regle que le depot livre n'a pas.
REGLE = "android/app/src/*/assets-slim/bundle/*.manifest.properties"

# Un nom de manifeste qui n'existe sur AUCUN disque. Il teste que la regle est GENERIQUE et non
# quatre litteraux : sans lui, ajouter jak3 ramenerait le defaut en silence.
SONDE = "sonde-jamais-ecrite"

SENTINELLE = "version=cSONDE-DE-REECRITURE"


def git(root, *args) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=str(root), capture_output=True,
                          text=True, timeout=180)


def dossiers_bundle(root) -> list[str]:
    """Les `bundle/` presents dans l'arbre, chemins RELATIFS. Lus sur le DISQUE, jamais codes
    en dur : c'est ce qui fait que jak2 est couvert sans etre nomme."""
    base = Path(root) / "android" / "app" / "src"
    out = []
    if base.is_dir():
        for jeu in sorted(p for p in base.iterdir() if p.is_dir()):
            d = jeu / "assets-slim" / "bundle"
            if d.is_dir():
                out.append(d.relative_to(Path(root)).as_posix())
    return out


def manifestes_suivis(root) -> list[str]:
    r = git(root, "ls-files", "--", REGLE)
    return [l for l in r.stdout.splitlines() if l.strip()]


def ignore(root, rel: str) -> bool:
    """`--no-index` : le chemin n'a pas besoin d'EXISTER, et un chemin encore SUIVI est quand
    meme confronte aux regles. Sans lui, git repond « non ignore » pour un fichier suivi et le
    bras d'AVANT accuserait la regle au lieu du suivi."""
    return git(root, "check-ignore", "-q", "--no-index", "--", rel).returncode == 0


def salete_bundle(root) -> list[str]:
    """La salete SOUS LES DOSSIERS DE PACK, et rien d'autre.

    On ne lit PAS tout `android/` (signalement 5 du 12/09) : un recensement qui assert
    `git status -- android` rougit pour le chantier de n'importe qui d'autre, pour une raison
    qui n'est pas la sienne. Le compte complet d'`android/` est PUBLIE a cote, jamais compte."""
    lignes = []
    for d in dossiers_bundle(root):
        r = git(root, "status", "--porcelain=v1", "-uall", "--", d)
        lignes += [l.strip() for l in r.stdout.splitlines() if l.strip()]
    return lignes


def defauts(root) -> list[str]:
    """Un defaut par ligne, chacun NOMMANT son chemin. Liste vide = la cible est tenue."""
    root = Path(root)
    out = [f"suivi:{p}" for p in manifestes_suivis(root)]

    dirs = dossiers_bundle(root)
    if not dirs:
        # LE PLANCHER DE VACUITE : sans dossier de pack, la garde ne mesure RIEN et un zero se
        # lirait « tenu ». C'est l'instrument qui est aveugle, et il le dit.
        out.append("instrument-aveugle:aucun-dossier-bundle")
    for d in dirs:
        jeu = Path(d).parts[3]
        for m in sorted(p.name for p in (root / d).glob("*.manifest.properties")):
            if not ignore(root, f"{d}/{m}"):
                out.append(f"non-ignore:{d}/{m}")
        futur = f"{d}/{jeu}_{SONDE}.manifest.properties"
        if not ignore(root, futur):
            out.append(f"regle-non-generique:{futur}")

    out += [f"bundle-sale:{l}" for l in salete_bundle(root)]
    return out


def sonde_reecriture(root) -> dict:
    """FABRIQUER LE DEFAUT : rejouer ce que fait le build, et regarder l'arbre.

    Les manifestes sont reecrits (version remplacee par une sentinelle), la salete des dossiers
    de pack est mesuree, puis les OCTETS ET LA DATE d'origine sont remis. La restitution est
    verifiee par empreinte ; un echec de restitution est lui-meme un defaut, jamais un silence.
    """
    root = Path(root)
    cibles = [root / d / m.name
              for d in dossiers_bundle(root)
              for m in sorted((root / d).glob("*.manifest.properties"))]
    photo = [(p, p.read_bytes(), (p.stat().st_atime, p.stat().st_mtime)) for p in cibles]
    sale: list[str] = []
    try:
        for p, octets, _ in photo:
            lignes = [SENTINELLE if l.startswith("version=") else l
                      for l in octets.decode("utf-8", "replace").splitlines()]
            p.write_text("\n".join(lignes) + "\n", encoding="utf-8")
        sale = salete_bundle(root)
    finally:
        rendus = 0
        for p, octets, temps in photo:
            try:
                p.write_bytes(octets)
                import os
                os.utime(p, temps)
                rendus += 1
            except OSError:
                pass
    intacts = sum(1 for p, octets, _ in photo if p.read_bytes() == octets)
    return {"reecrits": len(photo), "sale": sale, "rendus": rendus, "intacts": intacts}


def semer(d, suivi: bool) -> Path:
    """Un depot JETABLE portant le cas voulu. UNE source pour les deux bras du banc.

    `suivi=True` reproduit l'etat d'AVANT : le manifeste est commite et aucune regle ne le
    couvre. `suivi=False` reproduit la cible : meme fichier sur le disque, regle posee, rien
    dans l'index."""
    d = Path(d)
    bundle = d / "android/app/src/jak1/assets-slim/bundle"
    bundle.mkdir(parents=True, exist_ok=True)
    (bundle / "jak1_cgo.manifest.properties").write_text(
        "# Generated by android/build_cgo_pack.sh — do not edit.\n"
        "version=c0000000000\ngame=jak1\nfile_count=74\n", encoding="utf-8")
    (d / ".gitignore").write_text("" if suivi else REGLE + "\n", encoding="utf-8")
    git(d, "init", "-q")
    git(d, "add", "--", ".gitignore")
    if suivi:
        git(d, "add", "-f", "--", "android")
    git(d, "-c", "user.name=banc", "-c", "user.email=banc@local",
        "-c", "commit.gpgsign=false", "commit", "-q", "-m", "semis")
    return d


if __name__ == "__main__":
    import sys
    racine = sys.argv[1] if len(sys.argv) > 1 else "."
    mauvais = defauts(racine)
    for m in mauvais:
        print(m)
    sys.exit(1 if mauvais else 0)
