#!/usr/bin/env bash
# scripts/shell/build_enhanced_models.sh
#
# CONDITIONAL "enhanced HD models" asset-bake for jak1 (autoport Grecharged-hd-models).
#
# ROUND 3 / BRICK 2 REWRITE — SURGICAL merc swap, NOT a level rebake.
# --------------------------------------------------------------------------
# Round 2 baked the enhanced fr3 by RE-DECOMPILING the whole level from the ISO
# (a restricted DGO set) with the HD GLBs dropped into custom_assets/.../merc_replacements/.
# That regenerated EVERY non-character draw of the level, and the restricted rebake does
# NOT reproduce the stock non-character data byte-for-byte (measured: GAME.fr3 diverges at
# a non-merc byte, village1.fr3 flips a texture byte 0x00->0xff) -> the owner's "tout violet"
# (all-magenta) ground. That was a whole-level bake-integrity failure, far bigger than a
# character texture problem.
#
# This rewrite instead loads the STOCK <level>.fr3 and swaps ONLY the named merc model(s)
# in memory via the existing decompiler::replace_model (the tools/hd_merc_swap CLI), then
# re-serializes. Every non-character draw is therefore byte-identical to stock BY
# CONSTRUCTION; an explicit INTEGRITY GATE (hd_merc_swap diff) proves it and refuses to ship
# on any non-character divergence. The stock fr3 in out/jak1/fr3/ are READ ONLY and never
# touched (no backup/restore/trap needed anymore).
#
# The 4 HD character GLBs live in recharged_assets/hd_models/ (regenerated by brick 1 with
# authored PS2 normals + UV-split preserved). They already carry their merc-ctrl <name>-lod0
# identity, so no jak2 ISO re-rip is needed at bake time — the bake depends only on the
# committed GLBs + the stock jak1 fr3.
#
#      eichar-lod0    = Jak    -> COMMON   -> GAME.fr3
#      sidekick-lod0  = Daxter -> COMMON   -> GAME.fr3
#      sage-lod0      = Samos  -> village1 -> village1.fr3
#      assistant-lod0 = Keira  -> village1 -> village1.fr3
#
# CONDITIONAL: if the staged HD GLBs are absent, this is a NO-OP success (exit 0) — jak1
# then builds STOCK and the in-game toggle stays hidden.
#
# IDEMPOTENT: out/jak1/fr3/enhanced/ is recreated fresh each run; nothing else is mutated.
#
# This script does NOT touch goal_src / game / decompiler source — it only orchestrates the
# offline hd_merc_swap tool and writes the enhanced fr3 overlay.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
ROOT="$(pwd)"

log(){ echo "[enhanced-models] $*"; }

STAGE_DIR="recharged_assets/hd_models"
FR3_DIR="out/jak1/fr3"
ENHANCED_OUT="$FR3_DIR/enhanced"
SWAP_BIN="build/tools/hd_merc_swap/hd_merc_swap"

# The merc-ctrl names whose "Replacing <name> for <lvl>" line MUST appear, and their target fr3.
REPLACE_NAMES=(eichar-lod0 sidekick-lod0 sage-lod0 assistant-lod0)

# ---------------------------------------------------------------------------
# 1. GLB gate — absence is a VALID state (no-op success): jak1 builds stock.
# ---------------------------------------------------------------------------
for n in "${REPLACE_NAMES[@]}"; do
  if [ ! -f "$STAGE_DIR/$n.glb" ]; then
    log "staged HD GLB $STAGE_DIR/$n.glb absent — skipping enhanced HD bake (jak1 builds stock, toggle stays hidden)"
    exit 0
  fi
done

# ---------------------------------------------------------------------------
# 2. Require the stock FR3 (read-only source of the swap).
# ---------------------------------------------------------------------------
for f in GAME.fr3 village1.fr3; do
  if [ ! -f "$FR3_DIR/$f" ]; then
    log "stock $FR3_DIR/$f missing — run the normal jak1 decomp first"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# 3. Ensure the surgical swap tool is built.
# ---------------------------------------------------------------------------
if [ ! -x "$SWAP_BIN" ]; then
  log "building hd_merc_swap tool…"
  cmake --build build --target hd_merc_swap -j"$(nproc)" \
    || { log "failed to build $SWAP_BIN — configure the desktop 'build' tree first"; exit 1; }
fi
[ -x "$SWAP_BIN" ] || { log "$SWAP_BIN missing after build"; exit 1; }

# ---------------------------------------------------------------------------
# 4. Fresh enhanced overlay dir.
# ---------------------------------------------------------------------------
rm -rf "$ENHANCED_OUT"
mkdir -p "$ENHANCED_OUT"

# ---------------------------------------------------------------------------
# 5. Surgical swaps. Each writes a fresh enhanced fr3 from the STOCK fr3, swapping ONLY the
#    named merc model(s). replace_model emits the "Replacing <name> for <lvl>: …" line.
# ---------------------------------------------------------------------------
SWAP_LOG="$(mktemp)"
log "surgical merc swap: GAME.fr3 (Jak=eichar-lod0, Daxter=sidekick-lod0)…"
"$SWAP_BIN" swap "$FR3_DIR/GAME.fr3" "$ENHANCED_OUT/GAME.fr3" \
  eichar-lod0="$STAGE_DIR/eichar-lod0.glb" \
  sidekick-lod0="$STAGE_DIR/sidekick-lod0.glb" 2>&1 | tee -a "$SWAP_LOG"
log "surgical merc swap: village1.fr3 (Samos=sage-lod0, Keira=assistant-lod0)…"
"$SWAP_BIN" swap "$FR3_DIR/village1.fr3" "$ENHANCED_OUT/village1.fr3" \
  sage-lod0="$STAGE_DIR/sage-lod0.glb" \
  assistant-lod0="$STAGE_DIR/assistant-lod0.glb" 2>&1 | tee -a "$SWAP_LOG"

# VERIFY all 4 swaps fired.
MISSING=()
for n in "${REPLACE_NAMES[@]}"; do
  if ! grep -qE "Replacing ${n}( |:)" "$SWAP_LOG"; then
    MISSING+=("$n")
  fi
done
rm -f "$SWAP_LOG"
if [ "${#MISSING[@]}" -ne 0 ]; then
  log "swap verification FAILED — no 'Replacing …' line for: ${MISSING[*]}"
  rm -rf "$ENHANCED_OUT"
  exit 1
fi
log "all ${#REPLACE_NAMES[@]} HD swaps confirmed."

# ---------------------------------------------------------------------------
# 6. INTEGRITY GATE — every non-character draw in the enhanced fr3 MUST be byte-identical to
#    stock (this is the anti-magenta guarantee). Refuse to ship on any divergence.
# ---------------------------------------------------------------------------
for f in GAME.fr3 village1.fr3; do
  if "$SWAP_BIN" diff "$FR3_DIR/$f" "$ENHANCED_OUT/$f" | grep -q "INTEGRITY PASS"; then
    log "integrity gate PASS for $f (non-character draws byte-identical to stock)."
  else
    log "INTEGRITY GATE FAILED for $f — non-character draws differ from stock. Refusing to ship."
    rm -rf "$ENHANCED_OUT"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# 7. village2.fr3 — ship a stock-identical copy to OVERWRITE any round-1 stale garbled
#    overlay on an in-place owner update (behaviorally identical to stock either way).
# ---------------------------------------------------------------------------
if [ -f "$FR3_DIR/village2.fr3" ]; then
  cp -p "$FR3_DIR/village2.fr3" "$ENHANCED_OUT/village2.fr3"
  log "stock-identical enhanced/village2.fr3 shipped (kills round-1 stale garbled overlay)"
fi

# ---------------------------------------------------------------------------
# 8. Summary. The stock fr3 in out/jak1/fr3/ were never modified.
# ---------------------------------------------------------------------------
log "DONE — enhanced HD set written to $ENHANCED_OUT/ (stock fr3 untouched):"
for f in GAME.fr3 village1.fr3 village2.fr3; do
  if [ -f "$ENHANCED_OUT/$f" ]; then
    printf '[enhanced-models]     enhanced/%-14s %s bytes\n' "$f" "$(stat -c %s "$ENHANCED_OUT/$f")"
  fi
done
log "enhanced/ is the OPTIONAL overlay shipped for the hd-models toggle; stock stays byte-identical."
