#!/usr/bin/env bash
# scripts/shell/build_enhanced_models.sh
#
# CONDITIONAL "enhanced HD models" asset-bake for jak1 (autoport Grecharged-hd-models).
#
# ROUND 3 / BRICK 2 REWRITE — SURGICAL merc swap, NOT a level rebake.
# --------------------------------------------------------------------------
# Round 2 baked the enhanced fr3 by RE-DECOMPILING the whole level from the ISO
# (a restricted DGO set) with the HD GLBs dropped into custom_assets/.../merc_replacements/.
# That regenerated EVERY non-character draw of the level, and the restricted rebake does
# NOT reproduce the stock non-character data byte-for-byte (measured: GAME.fr3 diverges at
# a non-merc byte, village1.fr3 flips a texture byte 0x00->0xff) -> the owner's "tout violet"
# (all-magenta) ground. That was a whole-level bake-integrity failure, far bigger than a
# character texture problem.
#
# This rewrite instead loads the STOCK <level>.fr3 and swaps ONLY the named merc model(s)
# in memory via the existing decompiler::replace_model (the tools/hd_merc_swap CLI), then
# re-serializes. Every non-character draw is therefore byte-identical to stock BY
# CONSTRUCTION; an explicit INTEGRITY GATE (hd_merc_swap diff) proves it and refuses to ship
# on any non-character divergence. The stock fr3 in out/jak1/fr3/ are READ ONLY and never
# touched (no backup/restore/trap needed anymore).
#
# The 4 HD character GLBs live in recharged_assets/hd_models/ (regenerated by brick 1 with
# authored PS2 normals + UV-split preserved). They already carry their merc-ctrl <name>-lod0
# identity, so no jak2 ISO re-rip is needed at bake time — the bake depends only on the
# committed GLBs + the stock jak1 fr3.
#
#      eichar-lod0    = Jak    -> COMMON -> GAME.fr3
#      sidekick-lod0  = Daxter -> COMMON -> GAME.fr3
#      sage-lod0      = Samos  -> COMMON -> GAME.fr3   (cycle 3: was village1.fr3)
#      assistant-lod0 = Keira  -> COMMON -> GAME.fr3   (cycle 3: was village1.fr3)
#
# CYCLE-3 FLICKER FIX: keira-hd/samos-hd used to live in village1.fr3, a STREAMED level —
# Loader::get_merc_model returns null the moment village1 leaves memory (level swaps in/around
# cinematics), the companion then submits found=0, the suppression TTL is not re-armed, and the
# actor blacks out for ~2 frames = the owner's cycle-3 NPC flicker (Jak/Daxter, in the always-
# resident GAME.fr3, were immune). ALL FOUR HD models now ride GAME.fr3; village1.fr3 ships a
# stock-identical enhanced copy that OVERWRITES the old overlay (avoids a stale second copy of
# keira-hd/samos-hd on in-place pack updates).
#
# CONDITIONAL: if the staged HD GLBs are absent, this is a NO-OP success (exit 0) — jak1
# then builds STOCK and the in-game toggle stays hidden.
#
# IDEMPOTENT: out/jak1/fr3/enhanced/ is recreated fresh each run; nothing else is mutated.
#
# This script does NOT touch goal_src / game / decompiler source — it only orchestrates the
# offline hd_merc_swap tool and writes the enhanced fr3 overlay.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
ROOT="$(pwd)"

log(){ echo "[enhanced-models] $*"; }

STAGE_DIR="recharged_assets/hd_models"
FR3_DIR="out/jak1/fr3"
ENHANCED_OUT="$FR3_DIR/enhanced"
SWAP_BIN="build/tools/hd_merc_swap/hd_merc_swap"

# M4: the canonical HD character set —
#   "<char>|<donor rip GLB>|<target level fr3>|<donor fr3>|<donor model>|<driver stock model>|<driver fr3>".
# 7th field <driver fr3>: fr3 the driver stock model lives in — EMPTY means it is in the target fr3
# (keira/samos are appended to GAME.fr3 but their drivers only exist in village1.fr3).
# Each entry is APPENDED (never re-rig REPLACEd) as merc model <char>-lod0 into the target fr3.
# Cycle 2: the donor rip is STAMPED first (hd_merc_swap stamp) with the donor fr3's exact
# per-draw GS modes / eye slots / effect indices (defect classes C/E/A: see-through fur+jaw+hair
# came from the lossy GLB alphaMode round-trip; white eyes from the dropped eye_id), and the
# append remaps donor eye slots onto the DRIVER's (--eye-from).
# Per-entry IP gate: a missing donor rip is a loud SKIP, not a failure.
#
# CYCLE 4 (blink): each donor fr3 also carries the character's EYELID texture, which NO merc draw
# references (the lid is drawn by EyeRenderer, not by the merc). LID_TEX[<char>] names that donor
# texture; `hd_merc_swap add --port-lid <name>` copies it into the enhanced fr3 under the
# debug_name "<char>-lid" that Merc2 looks up to hand the lid to EyeRenderer.
declare -A LID_TEX=(
  [jak-hd]=jak-orig-eyelid
  [dax-hd]=daxter-eyelid
  [keira-hd]=keira-eyelid
  [samos-hd]=samos-eyelid
  [jak2-hd]=jakb-eyelid
  [jak3-hd]=jakchires-eyelid
  [daxp-hd]=daxter-eyelid
  [keira3-hd]=keira-eyelid
  [ysamos-hd]=samos-eyelid
  [jakm-hd]=jakchires-eyelid
  [jakp-hd]=jakb-eyelid
)
# CYCLE 5 item 1 (Jak 3 MASQUE BAISSÉ = BARE FACE): jak3 has NO separate unmasked art-group — the
# jakc donor carries the mask BOTH ways, as TWO SEPARATE SCARF EFFECTS on jakc-highres-lod0 (the
# same donor as jak3-hd):
#     effect[0]  = the static scarf pulled UP OVER THE NOSE  (the masked look)
#     effect[17] = the scarf hanging at the NECK             (the bare-face look)
# Our renderer force-enables EVERY effect, so both scarves always drew and the face was never bare
# (jakm-hd came out pixel-identical to jak3-hd). jakm-hd is therefore the same donor appended with
#     --drop-effect 0          -> the scarf-over-the-nose geometry is gone from the model entirely
#     --strip-target 15/22/23  -> those donor blerc targets are removed from the RUNTIME channel map
#                                 (15 lowers the goggles; 22 and 23 RAISE the neck scarf back toward
#                                 the face) so nothing can pull the mask back up at runtime
# and with NO BAKE: the goggles stay at the FOREHEAD, which is the authentic bare-face cutscene
# state. (The old --bake-blerc-target 15 wiring is retired for jakm-hd; the BAKE mechanism itself is
# kept below for future looks, and its amplitude bug is fixed — the runtime full-on channel weight
# is 4096, see goal_src/jak1/engine/gfx/foreground/bones.gc:888-897, so a bake at weight 1.0 was
# 4096x too small to see. hd_merc_swap now bakes at --bake-weight, default 4096.)
declare -A BAKE_TARGET=(
)
# Gkeira-hd-detached-parts (owner 2026-08-28): "le modele de Keira HD il a une visiere attachee, a
# genre quelques metres du main modele [...] dans Jak 1 ca sert a rien, faut que tu vires cette
# partie" -> "la visiere faut la supprimer, rien a foutre la".
# The jak2/jak3 Keira donors carry a WELDING MASK prop she does not wear: two joints, `mask` and
# `maskstrap`, parented to `prejoint` (the ROOT, not the head) and posed at the model ORIGIN, at and
# below the soles of her feet. Measured on out/jak1/fr3/skin/keira-hd-lod0.glb (bind space, model
# 3.1364 units tall, feet at y=0):
#     maskstrap  100 verts, y -0.0313 .. 0.0410   textures keira-brownstraps-new + keira-maskbolt
#     mask        73 verts, y -0.4095 .. 0.0578   texture  keira-mask
# and they are the WHOLE of their merc effects — no other joint owns a vertex in them, so dropping
# the effects removes exactly the prop and nothing else. `mask` alone sets the model's bbox floor:
# without it the drawn mesh starts at her soles instead of 0.41 units under the ground.
# NOT touched: the goggles she really wears (gogglesBase/Mid/Left/Right, textures keira-glasses /
# keira-gogglestrap / keira-lens-large, at y 1.98..2.20, i.e. on her head) and the welding TORCH,
# which retargets onto jak1's own `torch` joint and is used in village1.
# The two donors number their effects differently — indices verified per model by
# `hd_merc_swap audit`, never assumed:
#     keira-hd  effect[0] = maskstrap (88+96 tris)   effect[5] = mask (96 tris)
#     keira3-hd effect[1] = maskstrap (88+96 tris)   effect[5] = mask (96 tris)
# keira3-hd is the SUPERVISOR's extension of the owner's order: same character, same LOOK menu,
# same parasite, same one-line fix. Delete its line to keep the mask on the JAK 3 Keira look.
#
# Per-model EXTRA arguments spliced into the `hd_merc_swap add` invocation (word-split on purpose).
declare -A EXTRA_ADD_ARGS=(
  [jakm-hd]="--drop-effect 0 --strip-target 15 --strip-target 22 --strip-target 23"
  [keira-hd]="--drop-effect 0 --drop-effect 5"
  [keira3-hd]="--drop-effect 1 --drop-effect 5"
)
# CYCLE 5 item 3 (exhaustive inventory): one further cutscene-only Jak look the earlier sweeps
# missed — jakp-hd = the owner-named "Jak II PRISON" look (Jak 2 prison/experiments cutscenes,
# donor jak2 ldjakbrn). Plain append: no drop-effect, no blerc strip, no bake.
# A second candidate, jakf-hd (the jak3 ljkfeet "barefoot" look, boots replaced by foot wraps), was
# integrated in the same cycle and then REMOVED COMPLETELY on the owner's 2026-08-05 19:30 verdict
# (buggy and useless) — do not re-add it.
APPENDS=(
  "jak-hd|decompiler_out/jak2/levels/introcst/jakone-highres-lod0.glb|GAME|out/jak2/fr3/introcst.fr3|jakone-highres-lod0|eichar-lod0|"
  "dax-hd|decompiler_out/jak3/levels/ldax/daxter-highres-lod0.glb|GAME|out/jak3/fr3/ldax.fr3|daxter-highres-lod0|sidekick-lod0|"
  "keira-hd|decompiler_out/jak2/levels/lintcstb/keira-highres-lod0.glb|GAME|out/jak2/fr3/lintcstb.fr3|keira-highres-lod0|assistant-lod0|out/jak1/fr3/village1.fr3"
  "samos-hd|decompiler_out/jak3/levels/lsamos/samos-highres-lod0.glb|GAME|out/jak3/fr3/lsamos.fr3|samos-highres-lod0|sage-lod0|out/jak1/fr3/village1.fr3"
  "jak2-hd|decompiler_out/jak2/levels/ljakdax/jak-highres-lod0.glb|GAME|out/jak2/fr3/ljakdax.fr3|jak-highres-lod0|eichar-lod0|"
  "jak3-hd|decompiler_out/jak3/levels/ljakc/jakc-highres-lod0.glb|GAME|out/jak3/fr3/ljakc.fr3|jakc-highres-lod0|eichar-lod0|"
  "daxp-hd|decompiler_out/jak3/levels/loutro2/ottsel-daxpants-lod0.glb|GAME|out/jak3/fr3/loutro2.fr3|ottsel-daxpants-lod0|sidekick-lod0|"
  "keira3-hd|decompiler_out/jak3/levels/lkeira/keira-highres-lod0.glb|GAME|out/jak3/fr3/lkeira.fr3|keira-highres-lod0|assistant-lod0|out/jak1/fr3/village1.fr3"
  "ysamos-hd|decompiler_out/jak2/levels/lysamsam/youngsamos-highres-lod0.glb|GAME|out/jak2/fr3/lysamsam.fr3|youngsamos-highres-lod0|sage-lod0|out/jak1/fr3/village1.fr3"
  "jakm-hd|decompiler_out/jak3/levels/ljakc/jakc-highres-lod0.glb|GAME|out/jak3/fr3/ljakc.fr3|jakc-highres-lod0|eichar-lod0|"
  "jakp-hd|decompiler_out/jak2/levels/ldjakbrn/jak-highres-prison-lod0.glb|GAME|out/jak2/fr3/ldjakbrn.fr3|jak-highres-prison-lod0|eichar-lod0|"
)
# The fr3 that receive appends, in order.
APPEND_LEVELS=(GAME village1)

# The donor dump the HD art is derived from. jak1's 4 HD characters are ripped from the Jak 2
# dump (fr3_to_gltf on decompiler_out/jak2 <- iso_data/jak2). Named here so the IP gate is explicit.
DONOR_DUMP="iso_data/jak2"

# ---------------------------------------------------------------------------
# 0. ARCHITECTURE IP gate (owner 2026-08-02): the HD models derive from the user's Jak 2 dump =
#    Naughty Dog IP. HD may be generated ONLY if that dump is present. Absent -> the feature is
#    unavailable: NO bake, jak1 stays stock (no-op success). build.sh forces --hd-models OFF in the
#    same situation (byte-identical stock build); this is the defensive gate for a direct invocation.
# ---------------------------------------------------------------------------
if [ -z "$(find "$DONOR_DUMP" -maxdepth 2 -type f ! -name '.gitignore' -print -quit 2>/dev/null)" ]; then
  log "donor dump '$DONOR_DUMP' absent — the HD models are ND IP derived from it, so HD is unavailable; skipping enhanced HD bake (jak1 builds stock)"
  exit 0
fi
log "donor dump '$DONOR_DUMP' present — HD generation permitted (ND-derived assets ship EXTERNAL, never in the APK)"

# ---------------------------------------------------------------------------
# 1. ANIM-RETARGET (2026-08-03): prep the HD Jak merc GLB (jak-hd-lod0) from the donor rip, the SAME
#    75-joint prep as the jak-hd art-group (build_hd_jak_artgroup.sh) so the appended merc's bone
#    weights index the companion's skelgroup skeleton. We APPEND this (below) instead of the old
#    re-rig REPLACE of eichar/sidekick/sage/assistant — that REPLACE deformed the characters (the
#    owner's "carnage"). Donor rip absent -> stock (no-op success).
# ---------------------------------------------------------------------------
ANY_DONOR=0
for entry in "${APPENDS[@]}"; do
  IFS='|' read -r _c glb _lvl _dfr3 _dmdl _drv _dfr3b <<< "$entry"
  [ -f "$glb" ] && ANY_DONOR=1
done
if [ "$ANY_DONOR" -eq 0 ]; then
  log "no HD donor rip present for any HD character — skipping enhanced HD bake (jak1 builds stock, toggle hidden)"
  exit 0
fi
HD_TMP="$(mktemp -d)"
trap 'rm -rf "$HD_TMP"' EXIT

# ---------------------------------------------------------------------------
# 2. Require the stock FR3 (read-only source of the swap).
# ---------------------------------------------------------------------------
for f in GAME.fr3 village1.fr3; do
  if [ ! -f "$FR3_DIR/$f" ]; then
    log "stock $FR3_DIR/$f missing — run the normal jak1 decomp first"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# 3. Ensure the surgical swap tool is built.
# ---------------------------------------------------------------------------
if [ ! -x "$SWAP_BIN" ]; then
  log "building hd_merc_swap tool…"
  cmake --build build --target hd_merc_swap -j"$(nproc)" \
    || { log "failed to build $SWAP_BIN — configure the desktop 'build' tree first"; exit 1; }
fi
[ -x "$SWAP_BIN" ] || { log "$SWAP_BIN missing after build"; exit 1; }

# ---------------------------------------------------------------------------
# 4. Fresh enhanced overlay dir.
# ---------------------------------------------------------------------------
rm -rf "$ENHANCED_OUT"
mkdir -p "$ENHANCED_OUT"

# ---------------------------------------------------------------------------
# 5. APPEND stage. For each target level fr3 we start from the STOCK fr3 and chain one
#    `hd_merc_swap add` per character destined to that level (through intermediate tmp fr3),
#    writing the final result to enhanced/<lvl>.fr3. Append-only: NO re-rig replace, so every
#    stock character stays untouched. Per-character IP gate: missing donor rip -> loud SKIP.
# ---------------------------------------------------------------------------
APPENDED_LEVELS=()
for lvl in "${APPEND_LEVELS[@]}"; do
  SRC="$FR3_DIR/$lvl.fr3"
  n_app=0
  for entry in "${APPENDS[@]}"; do
    IFS='|' read -r char glb target donor_fr3 donor_model driver_model driver_fr3 <<< "$entry"
    [ "$target" = "$lvl" ] || continue
    if [ ! -f "$glb" ]; then
      log "SKIP $char — donor rip '$glb' absent (ND IP gate); $lvl.fr3 will not carry $char-lod0"
      continue
    fi
    # cycle 2: STAMP the rip with the donor fr3's exact draw modes / eye slots / effect indices.
    # The donor fr3 comes from the same dump as the rip; absence means a broken/partial decomp —
    # fail loudly rather than bake the lossy (see-through, white-eyed) round-trip again.
    if [ ! -f "$donor_fr3" ]; then
      log "FATAL: donor fr3 '$donor_fr3' missing for $char — cannot stamp draw modes/eye slots"
      rm -rf "$ENHANCED_OUT"; exit 1
    fi
    # ---- PHYSICS JOINT INJECTION (secondary-motion, 2026-08-13) ----------------------------
    # Same spec, same tool, same donor as scripts/shell/build_hd_actor_artgroup.sh — see the
    # long note there. The art-group and the baked mesh MUST agree on the joint list: physics
    # resolves its joints BY NAME against the art-group's jgeo, so a mesh with joints the art
    # group lacks moves nothing, and the reverse indexes past the end. One committed spec drives
    # both, so they cannot disagree.
    # No spec for a character => untouched donor, byte-identical passthrough.
    # Same STABLE path as build_hd_actor_artgroup.sh writes: <char>-k2e.json records the donor it
    # was built from, so the file must outlive the run. The injector is deterministic (no clock, no
    # randomness), so whichever script writes it last produces identical bytes.
    INJ_SPEC="recharged_assets/$char-inject-joints.txt"
    if [ -f "$INJ_SPEC" ]; then
      INJECTED="$FR3_DIR/skin/$char-donor-injected.glb"
      mkdir -p "$(dirname "$INJECTED")"
      python3 .autoport/physics_inject_joints.py --in "$glb" --out "$INJECTED" \
          --spec "$INJ_SPEC" --report "$HD_TMP/$char-inject.txt" >/dev/null 2>&1 \
        || { log "FATAL: joint injection of $char from '$INJ_SPEC' failed"; rm -rf "$ENHANCED_OUT"; exit 1; }
      log "inject: $char donor carries the physics joints of $INJ_SPEC"
      glb="$INJECTED"
    fi
    # ---- PROP JOINT REMOVAL (Gkeira-visor-deliver, owner 2026-08-29) ------------------------
    # « Keira HD a toujours la visiere attachee. » The welding-mask prop's DRAWN GEOMETRY is
    # removed below by EXTRA_ADD_ARGS/--drop-effect, and has been since 2026-08-28 — but its two
    # JOINTS stayed in the rig, so the art-group the game loads still declared the prop. The
    # removal runs HERE, on the same stable donor path build_hd_actor_artgroup.sh prunes, so the
    # art-group, the k2e table and this baked mesh cannot disagree on the joint list (exact same
    # reason the injection above lives at this point). No spec for a character => untouched donor.
    # It does NOT touch primitives: `hd_merc_swap stamp` (below) asserts prim-count == donor-draw-
    # count and per-prim tri counts, and --drop-effect mirrors onto a fresh donor-fr3 load.
    DROP_SPEC="recharged_assets/$char-drop-joints.txt"
    if [ -f "$DROP_SPEC" ]; then
      DROPPED="$FR3_DIR/skin/$char-donor-pruned.glb"
      case "$glb" in "$FR3_DIR/skin/"*) DROPPED="$glb";; esac
      mkdir -p "$(dirname "$DROPPED")"
      python3 scripts/shell/hd_drop_joints.py --in "$glb" --out "$DROPPED" \
          --spec "$DROP_SPEC" --report "$HD_TMP/$char-drop.txt" \
        || { log "FATAL: joint drop of $char from '$DROP_SPEC' failed"; rm -rf "$ENHANCED_OUT"; exit 1; }
      sed 's/^/    /' "$HD_TMP/$char-drop.txt" | while read -r l; do log "$l"; done
      glb="$DROPPED"
    fi

    STAMPED="$HD_TMP/$char-stamped.glb"
    "$SWAP_BIN" stamp "$donor_fr3" "$donor_model" "$glb" "$STAMPED" \
      || { log "STAMP of $char from '$donor_fr3' ($donor_model) failed"; rm -rf "$ENHANCED_OUT"; exit 1; }
    PREPPED="$HD_TMP/$char-lod0.glb"
    python3 scripts/shell/prep_hd_actor_glb.py --in "$STAMPED" --out "$PREPPED" >/dev/null 2>&1 \
      || { log "prep of $char-lod0.glb from '$STAMPED' failed"; rm -rf "$ENHANCED_OUT"; exit 1; }

    # ---- secondary-motion cycle 7: WEIGHT TRANSFER onto physics joints ----------------------
    # A chain only reaches the screen through the vertices its joint is weighted to.  The donor
    # artists painted some of those joints decoratively (keira-hd rBoob: 90 verts, peak weight
    # 0.408, dominant on ZERO of them), so the solver moved them correctly and almost nothing
    # moved on screen.  recharged_assets/physics_reskin.txt rescales the artist's own profile so
    # the joint actually owns its geometry.  No rule for a model = byte-identical passthrough.
    RESKIN_LOG="$HD_TMP/$char-reskin.txt"
    python3 .autoport/physics_c7_reskin.py --model "$char" --in "$PREPPED" --out "$PREPPED.reskin" \
      --report "$RESKIN_LOG" \
      || { log "reskin of $char-lod0.glb failed"; rm -rf "$ENHANCED_OUT"; exit 1; }
    mv -f "$PREPPED.reskin" "$PREPPED"

    # ---- RELIAISON DE PEAU D'UNE PIECE ACCROCHEE AU MAUVAIS OS (Gjak-hd-rig-strap, 2026-08-29) --
    # « la boucle en metal de la sangle dans son dos [...] semble attachee aux mouvements des
    # epaules, donc elle bouge separement de la sangle. » L'ilot de 8 sommets de la boucle est lie
    # a `LshoulderPad` alors que SIX de ses huit sommets sont geometriquement COINCIDENTS avec des
    # sommets de la sangle/sacoche lies a `chest` : deux positions identiques sur deux os
    # differents se separent des que ces os divergent. L'outil ADOPTE la liaison des jumeaux et
    # publie l'accord sommet par sommet.
    # Il tourne ICI, apres le prep et le reskin, donc sur les octets EXACTS que `hd_merc_swap add`
    # appende dans l'fr3 et que `skin-keep` conserve pour la mesure — les deux ne peuvent pas
    # diverger. Pas de spec pour un personnage => passe-plat identique au bit.
    # Il ne REPARENTE rien : une hierarchie ne voyage que par `<char>-ag.go`, dont le producteur
    # n'est appele par aucune chaine de livraison (celui du zip du 2026-08-30 datait du 08-05).
    REBIND_SPEC="recharged_assets/$char-rebind-skin.txt"
    if [ -f "$REBIND_SPEC" ]; then
      REBIND_LOG="$HD_TMP/$char-rebind.txt"
      python3 scripts/shell/hd_rebind_skin.py --in "$PREPPED" --out "$PREPPED.rebind" \
          --spec "$REBIND_SPEC" --report "$REBIND_LOG" \
        || { log "FATAL: reliaison de peau de $char depuis '$REBIND_SPEC' echouee:";
             sed 's/^/    /' "$REBIND_LOG" 2>/dev/null; rm -rf "$ENHANCED_OUT"; exit 1; }
      mv -f "$PREPPED.rebind" "$PREPPED"
      sed 's/^/    /' "$REBIND_LOG" | while read -r l; do log "$l"; done
    fi

    # LE MESH QUI PART REELLEMENT, GARDE HORS DU REPERTOIRE TEMPORAIRE (2026-08-13).
    # `HD_TMP` est un `mktemp -d` avec `trap rm -rf ... EXIT` (:164-165) : le glb PREPPE+RESKINNE —
    # le seul qui porte les poids reellement livres — etait detruit a la fin de chaque bake. Toute
    # mesure de peau retombait donc sur le rip BRUT du donneur, en amont du prep ET du reskin, et ne
    # pouvait par construction voir aucune correction de poids : `ROOM-SKINCOV` republiait tear=82
    # sur `rmidhair` apres le bake qui l'avait mis a zero. Ce n'est pas une mesure perimee, c'est une
    # mesure prise sur une AUTRE entree.
    # On le copie donc dans `out/` (ignore par git, .gitignore:44) avant que le trap ne parte. Ca ne
    # change RIEN a ce qui est bake — c'est une copie, apres coup, du fichier deja fige.
    SKIN_KEEP="$(dirname "$ENHANCED_OUT")/skin"
    mkdir -p "$SKIN_KEEP" 2>/dev/null || true
    cp -f "$PREPPED" "$SKIN_KEEP/$char-lod0.glb" 2>/dev/null \
      && log "skin-keep: $char-lod0.glb conserve pour la mesure ($SKIN_KEEP)" \
      || log "skin-keep: copie de $char-lod0.glb IMPOSSIBLE — la mesure de peau restera sur le rip brut"
    if grep -q '^  !!' "$RESKIN_LOG" 2>/dev/null; then
      log "RESKIN verification FAILED for $char — a declared transfer did not apply:"; cat "$RESKIN_LOG"
      rm -rf "$ENHANCED_OUT"; exit 1
    fi
    grep -qE '^\[reskin\]' "$RESKIN_LOG" 2>/dev/null && sed 's/^/    /' "$RESKIN_LOG" | while read -r l; do log "$l"; done

    n_app=$((n_app + 1))
    DST="$HD_TMP/$lvl.step$n_app.fr3"
    SWAP_LOG="$(mktemp)"
    log "anim-retarget: APPEND $char-lod0 to $lvl.fr3 (step $n_app, append-only, NO re-rig replace, eyes from $driver_model, blerc from $donor_model)…"
    # the driver stock model is resolved in the target fr3 unless the entry names another fr3
    # (keira/samos: appended to GAME.fr3, drivers only in village1.fr3).
    DRIVER_ARGS=()
    if [ -n "$driver_fr3" ]; then
      DRIVER_ARGS=(--driver-fr3 "$driver_fr3")
    fi
    # cycle 4 (blink): port the donor eyelid texture as "<char>-lid" for the EyeRenderer path.
    LID_ARGS=()
    LID_NAME="${LID_TEX[$char]:-}"
    if [ -z "$LID_NAME" ]; then
      log "FATAL: no LID_TEX entry for $char — the blink fix needs a donor eyelid texture name"
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    LID_ARGS=(--port-lid "$LID_NAME")
    # cycle-4 item 3: bake the donor's masked-look blend target into the appended verts (jakm-hd).
    BAKE_ARGS=()
    BAKE_N="${BAKE_TARGET[$char]:-}"
    if [ -n "$BAKE_N" ]; then
      case "$BAKE_N" in
        ''|*[!0-9]*) log "FATAL: BAKE_TARGET[$char]='$BAKE_N' is not a pinned target index"; rm -rf "$ENHANCED_OUT"; exit 1;;
      esac
      BAKE_ARGS=(--bake-blerc-target "$BAKE_N")
    fi
    # cycle-5 item 1: per-model extra args (jakm-hd: --drop-effect / --strip-target). Deliberately
    # UNQUOTED so the string word-splits into separate argv entries; empty when the model has none.
    EXTRA_ARGS=()
    EXTRA_STR="${EXTRA_ADD_ARGS[$char]:-}"
    if [ -n "$EXTRA_STR" ]; then
      # shellcheck disable=SC2206
      EXTRA_ARGS=($EXTRA_STR)
    fi
    "$SWAP_BIN" add "$SRC" "$PREPPED" "$DST" --eye-from "$driver_model" \
      --blerc-from "$donor_fr3:$donor_model" \
      ${DRIVER_ARGS[@]+"${DRIVER_ARGS[@]}"} "${LID_ARGS[@]}" \
      ${BAKE_ARGS[@]+"${BAKE_ARGS[@]}"} \
      ${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"} 2>&1 | tee -a "$SWAP_LOG"
    if ! grep -qE "APPENDED .*$char-lod0" "$SWAP_LOG"; then
      log "APPEND verification FAILED — no 'APPENDED … $char-lod0' line for $lvl.fr3."
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    # class A gate: the eye remap must have actually happened (donor rips DO carry eye draws)
    if ! grep -qE "EYE-REMAP: [1-9][0-9]* eye draws" "$SWAP_LOG"; then
      log "EYE-REMAP verification FAILED for $char — no eye draws were rebound to $driver_model."
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    # cycle-4 blink gate: the donor eyelid texture MUST have landed as "<char>-lid" (pool-safe),
    # otherwise Merc2 finds no lid texture and EyeRenderer keeps drawing the no-blink fallback.
    if ! grep -qE "^LID-PORT: '$LID_NAME' .* name='$char-lid' load_to_pool=0" "$SWAP_LOG"; then
      log "LID-PORT verification FAILED for $char — donor eyelid '$LID_NAME' was not ported as '$char-lid'."
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    # cycle-4 item 3 gate: the masked-look bake must have moved real vertices (loud fail otherwise).
    if [ -n "$BAKE_N" ] && ! grep -qE "^ *BLERC-BAKE: target=$BAKE_N .*verts_moved=[1-9]" "$SWAP_LOG"; then
      log "BLERC-BAKE verification FAILED for $char — target $BAKE_N moved no verts (masked look not baked)."
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    # class B gate: the blerc port must complete (or loudly state the donor carries no blerc)
    if ! grep -qE "BLERC-PORT OK|BLERC-PORT: donor has no blerc" "$SWAP_LOG"; then
      log "BLERC-PORT verification FAILED for $char — no blend-shape data was ported."
      rm -f "$SWAP_LOG"; rm -rf "$ENHANCED_OUT"; exit 1
    fi
    rm -f "$SWAP_LOG"
    SRC="$DST"
  done
  if [ "$n_app" -gt 0 ]; then
    cp "$SRC" "$ENHANCED_OUT/$lvl.fr3"
    APPENDED_LEVELS+=("$lvl.fr3")
    log "$n_app HD merc model(s) appended to enhanced/$lvl.fr3 (stock characters untouched)."
  else
    # No character could be appended to this level (all donors missing) — ship the STOCK copy so
    # it OVERWRITES any old cursed re-rig overlay left on the owner's device by a previous pack.
    if [ -f "$FR3_DIR/$lvl.fr3" ]; then
      cp -p "$FR3_DIR/$lvl.fr3" "$ENHANCED_OUT/$lvl.fr3"
      log "no HD donor for $lvl — stock-identical enhanced/$lvl.fr3 shipped (overwrites any old cursed overlay)"
    fi
  fi
done

# ---------------------------------------------------------------------------
# 6. INTEGRITY GATE — every non-character draw in each APPENDED enhanced fr3 MUST be
#    byte-identical to stock (this is the anti-magenta guarantee). Refuse to ship on divergence.
# ---------------------------------------------------------------------------
for f in "${APPENDED_LEVELS[@]-}"; do
  [ -n "$f" ] || continue
  if "$SWAP_BIN" diff "$FR3_DIR/$f" "$ENHANCED_OUT/$f" | grep -q "INTEGRITY PASS"; then
    log "integrity gate PASS for $f (non-character draws byte-identical to stock; HD merc appended)."
  else
    log "INTEGRITY GATE FAILED for $f — non-character draws differ from stock. Refusing to ship."
    rm -rf "$ENHANCED_OUT"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# 7. village2.fr3 — ship a stock-identical copy to OVERWRITE any round-1 stale garbled
#    overlay on an in-place owner update (behaviorally identical to stock either way).
#    (village1.fr3 carried keira-hd/samos-hd in cycles 1-2; since the cycle-3 flicker fix it is
#    a stock-identical copy written by the n_app=0 branch above — kept in APPEND_LEVELS so that
#    copy always ships and kills the stale two-copy hazard on in-place updates.)
# ---------------------------------------------------------------------------
if [ -f "$FR3_DIR/village2.fr3" ]; then
  cp -p "$FR3_DIR/village2.fr3" "$ENHANCED_OUT/village2.fr3"
  log "stock-identical enhanced/village2.fr3 shipped (kills round-1 stale garbled overlay)"
fi

# ---------------------------------------------------------------------------
# 8. Summary. The stock fr3 in out/jak1/fr3/ were never modified.
# ---------------------------------------------------------------------------
log "DONE — enhanced HD set written to $ENHANCED_OUT/ (stock fr3 untouched):"
for f in GAME.fr3 village1.fr3 village2.fr3; do
  if [ -f "$ENHANCED_OUT/$f" ]; then
    printf '[enhanced-models]     enhanced/%-14s %s bytes\n' "$f" "$(stat -c %s "$ENHANCED_OUT/$f")"
  fi
done
log "enhanced/ is the OPTIONAL overlay shipped for the hd-models toggle; stock stays byte-identical."
