#!/usr/bin/env bash
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"
fail(){ echo "[Gpbr FAIL] $*" >&2; exit 1; }
R=.autoport/reports/Grecharged-pbr-materials/report.txt
[ -f "$R" ] || fail "no report"
grep -qE '^RESULT: PASS' "$R" || fail "no explicit RESULT: PASS (WIP does not gate)"
grep -qiE '^RESULT: WIP' "$R" && fail "report is WIP"
D=.autoport/reports/Grecharged-pbr-materials/device
ls "$D"/*.mp4 >/dev/null 2>&1 || fail "no device video evidence"
ls "$D"/*.png >/dev/null 2>&1 || fail "no device still evidence"
grep -qiE 'magenta.*(scan|0 |zero|none|clean)' "$R" || fail "no magenta-scan result"
grep -qiE 'ndiff|mean_abs|mode.?0.*mode.?7|normal.*contribut' "$R" || fail "no normal-contribution (ndiff) proof"
grep -qiE 'per.?material|fallback' "$R" || fail "must implement the per-material fallback"
grep -qiE 'mood|current-sun|light-group|shadow-direction' "$R" || fail "PBR must be lit by the existing mood/TOD light env"
grep -qiE 'double.?dose|ignore.*baked|baked.*(ignored|removed|skipped)' "$R" || fail "PBR path must drop baked vertex lighting (no double-dose)"
grep -qiE 'off.*(stock|identical|byte)|stock.*off' "$R" || fail "OFF must == stock"
grep -qiE 'albedo|normal|roughness|metal|orm' "$R" || fail "must show the PBR material maps"
grep -qiE 'mCurrentFocus.*jak1|focus.*jak1' "$R" || fail "device jak1 evidence"
git status --porcelain .autoport/gold 2>/dev/null | grep -q . && fail "gold not pristine"
grep -qiE 'parallax|POM|height' "$R" || fail "no parallax/height (POM) evidence — owner mandate"
grep -qiE '\-112|sage.wall|owner.vantage' "$R" || fail "no proof at the owner's sage-wall vantage"
grep -qiE 'indirect|baked.*(gi|ambient|indirect)|macro.*(shading|luminance|profile)|correlation' "$R" || fail "no baked-GI/macro-shading reintegration evidence — owner round-3 mandate"
grep -qiE 'shadow.?map|depth.?map|PCF' "$R" || fail "no sun shadow-map evidence — owner round-4 mandate"
grep -qiE 'light.?group|multi.?light|moon|dir[012]' "$R" || fail "no multi-light (light-group/moon) evidence"
grep -qiE 'coverage|vis-alpha|tie|half.?pbr|unif' "$R" || fail "no coverage-unification evidence"
grep -qiE 'baked.?w|bakedw|baked.?weight|full.?realtime' "$R" || fail "no baked-weight full-realtime A/B evidence — owner round-4bis"
grep -qiE 'orbit|IoU|rotation.*(stable|pinned)|stable.*orbit' "$R" || fail "no camera-orbit shadow-stability proof — owner round-5"
grep -qiE 'raccord|matching|thatch|plank|sandstone|multi.?material' "$R" || fail "no matching multi-material evidence — owner round-5"
echo "[Gpbr PASS]"
