#!/usr/bin/env python3
"""Collect the measured desktop leg for the USB binary; never writes a proof file."""
import argparse
import hashlib
import json
import math
from pathlib import Path


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("proof", type=Path)
    parser.add_argument("--binary", type=Path, default=Path("build/game/gk"))
    parser.add_argument("--output", type=Path, default=Path("data/soft-baseline"))
    args = parser.parse_args()
    values = {}
    for line in args.proof.read_text().splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            values[key] = value
    binary_sha = sha(args.binary)
    required = {"source": "x86", "crash": "0", "soft_tile_target": "x86",
                "soft_tile_format": "R16_UNORM", "soft_tile_cost_gaps": "0"}
    for key, expected in required.items():
        if values.get(key) != expected:
            raise SystemExit(f"{key}: expected {expected}, observed {values.get(key)}")
    if values.get("sha") != binary_sha[:16]:
        raise SystemExit("The proof does not describe the supplied desktop binary")
    tiles = []
    for side in (64, 128):
        tile = {"side": side, "iterations": int(values[f"soft_tile_{side}_iterations"])}
        for field in ("upload_completion_ms", "raster_completion_ms"):
            tile[field] = float(values[f"soft_tile_{side}_{field}"])
            if not math.isfinite(tile[field]) or tile[field] <= 0:
                raise SystemExit(f"Invalid measurement: {side}/{field}")
        if tile["iterations"] <= 0:
            raise SystemExit("No measured iterations")
        tiles.append(tile)
    data = {"source": "x86", "crash": 0, "format": values["soft_tile_format"],
            "timer": values["soft_tile_timer"], "renderer": values["soft_tile_renderer"],
            "binary_sha256": binary_sha, "run_sha256": sha(args.proof),
            "started_at": values["started_at"], "tiles": tiles,
            "benchmark_source_sha256": sha(Path("game/graphics/opengl_renderer/soft_baseline.cpp"))}
    text = json.dumps(data, indent=2, sort_keys=True) + "\n"
    args.output.mkdir(parents=True, exist_ok=True)
    for name, content in (("x86_tiles.json", text), ("x86_tiles_json.h",
            '// Generated by tools/soft_bake/collect_tiles.py from a machine-produced desktop run.\n'
            '#pragma once\nnamespace soft_baseline_x86 {\n'
            'inline constexpr char json_text[] = R"softtiles(' + text + ')softtiles";\n}\n')):
        path = args.output / name
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(content)
        tmp.replace(path)
    print(json.dumps(data, sort_keys=True))


if __name__ == "__main__":
    main()
